### ISSUE TITLE
Optional Navigations Broken (Nullable object must have a value)

### ISSUE THREAD

**Issue by andy-clymer** [OData/AspNetCoreOData#1035] opened 2023-08-30 17:01 UTC
**Assemblies affected**
ASP.NET Core OData 8.2.2
.NET 7
EF Core 7.0.10

**Describe the bug**
When expanding a navigation property that can be nullable, and the result set returns at least one record that doesn't have a value set for this optional navigation (null), the following error is returned: Nullable object must have a value.

This works in version 8.2.0, but is broken in both the version listed above and 8.2.1.

**Reproduce steps**
1. Have a navigation property on your data model that is a related entity that is optional (nullable).
2. Either configure the property on the EDM entity type to be automatically expanded, or just add the property to your expand query parameter.
3. Ensure the result set returns at least one record that doesn't have a value set for this optional navigation.

**Data Model**
```csharp
public class User
{
    public User(string firstName, string lastName)
    {
        FirstName = firstName;
        LastName = lastName;
    }
    
    public Guid Id { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public int Age { get; set; }

    // Foreign Keys
    public Guid? VehicleId { get; set; }
    
    // Navigations
    public Vehicle? PrimaryVehicle { get; set; }
}
```

**EDM (CSDL) Model**
```xml
<?xml version="1.0" encoding="utf-8"?>
<edmx:Edmx Version="4.0" xmlns:edmx="http://docs.oasis-open.org/odata/ns/edmx">
  <edmx:DataServices>
    <Schema Namespace="ODataSample.Data" xmlns="http://docs.oasis-open.org/odata/ns/edm">
      <EntityType Name="User">
        <Key>
          <PropertyRef Name="id" />
        </Key>
        <Property Name="id" Type="Edm.Guid" Nullable="false" />
        <Property Name="firstName" Type="Edm.String" Nullable="false" />
        <Property Name="lastName" Type="Edm.String" Nullable="false" />
        <Property Name="age" Type="Edm.Int32" Nullable="false" />
        <Property Name="vehicleId" Type="Edm.Guid" />
        <NavigationProperty Name="primaryVehicle" Type="ODataSample.Data.Vehicle">
          <ReferentialConstraint Property="vehicleId" ReferencedProperty="id" />
        </NavigationProperty>
      </EntityType>
      <EntityType Name="Vehicle">
        <Key>
          <PropertyRef Name="id" />
        </Key>
        <Property Name="id" Type="Edm.Guid" Nullable="false" />
        <Property Name="make" Type="Edm.String" Nullable="false" />
        <Property Name="model" Type="Edm.String" Nullable="false" />
        <Property Name="color" Type="Edm.String" Nullable="false" />
      </EntityType>
    </Schema>
    <Schema Namespace="Default" xmlns="http://docs.oasis-open.org/odata/ns/edm">
      <EntityContainer Name="Container">
        <EntitySet Name="Users" EntityType="ODataSample.Data.User">
          <NavigationPropertyBinding Path="primaryVehicle" Target="Vehicles" />
        </EntitySet>
        <EntitySet Name="Vehicles" EntityType="ODataSample.Data.Vehicle" />
      </EntityContainer>
    </Schema>
  </edmx:DataServices>
</edmx:Edmx>
```
```csharp
public static IEdmModel GetEdmModelV1()
  {
      var builder = new ODataConventionModelBuilder();
      builder.EnableLowerCamelCase();

      // Users
      var userSet = builder.EntitySet<User>("Users");
      var userType = userSet.EntityType;
      userType.HasKey(t => t.Id);
      userType.Property(t => t.FirstName);
      userType.Property(t => t.LastName);
      userType.Property(t => t.Age);
      userType.Property(t => t.VehicleId);
      userType.HasOptional(t => t.PrimaryVehicle);

      // Vehicles
      var vehicleSet = builder.EntitySet<Vehicle>("Vehicles");
      var vehicleType = vehicleSet.EntityType;
      vehicleType.HasKey(t => t.Id);
      vehicleType.Property(t => t.Make);
      vehicleType.Property(t => t.Model);
      vehicleType.Property(t => t.Color);

      return builder.GetEdmModel();
  }
```

**Request/Response**
Request Uri:
> https://localhost:7012/v1/Users?$expand=primaryVehicle

Response:
> Status Code: 500 - Nullable object must have a value.

**Expected behavior**
Expected behavior is to return a response of the queried records that have the optional navigation set if they contain a value and for records that don't have a value set to also be returned. This would make querying work with optional navigations work like it did in version 8.2.0.

**Additional context**
System.InvalidOperationException: Nullable object must have a value.
         at System.Nullable`1.get_Value()
         at lambda_method18(Closure, QueryContext, DbDataReader, ResultContext, SplitQueryResultCoordinator)
         at Microsoft.EntityFrameworkCore.Query.Internal.SplitQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
         at System.Text.Json.Serialization.Converters.IAsyncEnumerableOfTConverter`2.OnWriteResume(Utf8JsonWriter writer, TAsyncEnumerable value, JsonSerializerOptions options, WriteStack& state)
         at System.Text.Json.Serialization.JsonCollectionConverter`2.OnTryWrite(Utf8JsonWriter writer, TCollection value, JsonSerializerOptions options, WriteStack& state)
         at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
         at System.Text.Json.Serialization.JsonConverter`1.WriteCore(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
         at System.Text.Json.Serialization.JsonConverter`1.WriteCoreAsObject(Utf8JsonWriter writer, Object value, JsonSerializerOptions options, WriteStack& state)
         at System.Text.Json.JsonSerializer.WriteCore[TValue](Utf8JsonWriter writer, TValue& value, JsonTypeInfo jsonTypeInfo, WriteStack& state)
         at System.Text.Json.JsonSerializer.WriteStreamAsync[TValue](Stream utf8Json, TValue value, JsonTypeInfo jsonTypeInfo, CancellationToken cancellationToken)
         at System.Text.Json.JsonSerializer.WriteStreamAsync[TValue](Stream utf8Json, TValue value, JsonTypeInfo jsonTypeInfo, CancellationToken cancellationToken)
         at System.Text.Json.JsonSerializer.WriteStreamAsync[TValue](Stream utf8Json, TValue value, JsonTypeInfo jsonTypeInfo, CancellationToken cancellationToken)
         at Microsoft.AspNetCore.Mvc.Formatters.SystemTextJsonOutputFormatter.WriteResponseBodyAsync(OutputFormatterWriteContext context, Encoding selectedEncoding)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|30_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeResultFilters>g__Awaited|28_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
         at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
         at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
         at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
         at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
         at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)

**Comment by xuzhg** [comment] 2023-08-30 20:52
It's a regression coming from https://github.com/OData/AspNetCoreOData/pull/993
The root cause is from https://github.com/OData/AspNetCoreOData/blob/main/src/Microsoft.AspNetCore.OData/Query/Expressions/SelectExpandBinder.cs#L463-L464 in the new method named "RemoveNonStructucalProperties".

There's a StackOverflow question [here](https://stackoverflow.com/questions/76998777/nullable-foreign-key-causes-runtime-error-in-odata-service). I can reproduce it using the sample provided [here](https://github.com/codeblock88/temp)

From the sample data: 
![image](https://github.com/OData/AspNetCoreOData/assets/9426627/069d08f9-ca51-4808-b77f-9ccfffa43ee4)

You can see User(1) and User(3) have 'null' DataFileRef. 

With the #993 changes, the LINQ expression has changed from left to right as below:

![image](https://github.com/OData/AspNetCoreOData/assets/9426627/5d531973-d316-437e-a8e4-2895368fc851)

The exception is thrown from the lines in the "black rectangle of the right picture", since "$$it.FileRefNavigation" is null for User(1) and User(3).

My suggestion:

1) The method of 'RemoveNonStructucalProperties' is over-coded for the LINQ expression, which makes the LINQ expression complex.
2) It will be a perf bottleneck if the schema is big (a lot of properties in one type). LINQ expression will be big, and two foreach are time-consuming.
3) It doesn't take the query setting into consideration.

**Comment by goatrodeosoftware** [comment] 2023-08-30 20:57
I've also produced this bug with optional references and have been unable to solve the issue with marking properties as optional in the OData definition.

**Comment by xuzhg** [comment] 2023-08-30 20:59
@goatrodeosoftware @andy-clymer see my previous comments.

**Comment by goatrodeosoftware** [comment] 2023-08-30 21:00
@xuzhg What would I see about your post? I read it and understand and was hoping to show that I experienced it and couldn't get around it with OData configuration.

**Comment by xuzhg** [comment] 2023-08-30 21:04
> @xuzhg What would I see about your post? I read it and understand and was hoping to show that I experienced it and couldn't get around it with OData configuration.

I can build a nightly for you to try it if you are interested. Just let me know. We hope we can fix it as soon as possible and release the official bit.

**Comment by xuzhg** [comment] 2023-08-30 22:30
@andy-clymer @goatrodeosoftware can you try the nightly Microsoft.AspNetCore.OData 8.9.0-Nightly202308302217

**Comment by goatrodeosoftware** [comment] 2023-08-30 23:23
@xuzhg I'm sorry, I misunderstood you- I didn't mean that you had to fix something right away to satisfy what I needed, just trying to add info in case it helps. Looks like you've already got it under control. As for me I can just use 8.2.0. I'm happy to try that, but I don't see the package in nuget- does that refer to a branch I'd need to download and reference instead of the nuget packaeg?

**Comment by xuzhg** [comment] 2023-08-31 00:36
> @xuzhg I'm sorry, I misunderstood you- I didn't mean that you had to fix something right away to satisfy what I needed, just trying to add info in case it helps. Looks like you've already got it under control. As for me I can just use 8.2.0. I'm happy to try that, but I don't see the package in nuget- does that refer to a branch I'd need to download and reference instead of the nuget package?

It doesn't matter. If you want to try the nightly (it's not on Nuget.org, but on Myget.Org), see the guides at https://github.com/OData/aspNetCoreOData/#34-nightly-builds .

**Comment by andy-clymer** [comment] 2023-08-31 01:23
> @andy-clymer @goatrodeosoftware can you try the nightly Microsoft.AspNetCore.OData 8.9.0-Nightly202308302217

@xuzhg Thanks for the quick response and action on this issue. I tried the nightly build that you referenced, and now receive a new error: Argument types do not match. The result still returns okay when this property isn't expanded, however the error arises now whenever I request expansion on that property, even if I only filter to return records that have a value set for the optional navigation.

** Stack Trace**
System.ArgumentException: Argument types do not match
   at System.Linq.Expressions.Expression.Condition(Expression test, Expression ifTrue, Expression ifFalse)
   at Microsoft.AspNetCore.OData.Query.Expressions.SelectExpandBinder.RemoveNonStructucalProperties(QueryBinderContext context, Expression source, IEdmStructuredType structuredType)
   at Microsoft.AspNetCore.OData.Query.Expressions.SelectExpandBinder.ProjectElement(QueryBinderContext context, Expression source, SelectExpandClause selectExpandClause, IEdmStructuredType structuredType, IEdmNavigationSource navigationSource)
   at Microsoft.AspNetCore.OData.Query.Expressions.SelectExpandBinder.BindSelectExpand(SelectExpandClause selectExpandClause, QueryBinderContext context)
   at Microsoft.AspNetCore.OData.Query.Expressions.BinderExtensions.ApplyBind(ISelectExpandBinder binder, IQueryable source, SelectExpandClause selectExpandClause, QueryBinderContext context)
   at Microsoft.AspNetCore.OData.Query.SelectExpandQueryOption.ApplyTo(IQueryable queryable, ODataQuerySettings settings)
   at Microsoft.AspNetCore.OData.Query.ODataQueryOptions.ApplySelectExpand[T](T entity, ODataQuerySettings querySettings)
   at Microsoft.AspNetCore.OData.Query.ODataQueryOptions.ApplyTo(IQueryable query, ODataQuerySettings querySettings)
   at Microsoft.AspNetCore.OData.Query.EnableQueryAttribute.ApplyQuery(IQueryable queryable, ODataQueryOptions queryOptions)
   at Microsoft.AspNetCore.OData.Query.EnableQueryAttribute.ExecuteQuery(Object responseValue, IQueryable singleResultCollection, ControllerActionDescriptor actionDescriptor, HttpRequest request)
   at Microsoft.AspNetCore.OData.Query.EnableQueryAttribute.OnActionExecuted(ActionExecutedContext actionExecutedContext, Object responseValue, IQueryable singleResultCollection, ControllerActionDescriptor actionDescriptor, HttpRequest request)
   at Microsoft.AspNetCore.OData.Query.EnableQueryAttribute.OnActionExecuted(ActionExecutedContext actionExecutedContext)
   at Microsoft.AspNetCore.Mvc.Filters.ActionFilterAttribute.OnActionExecutionAsync(ActionExecutingContext context, ActionExecutionDelegate next)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)

**Comment by xuzhg** [comment] 2023-08-31 01:25
> > @andy-clymer @goatrodeosoftware can you try the nightly Microsoft.AspNetCore.OData 8.9.0-Nightly202308302217
> 
> @xuzhg Thanks for the quick response and action on this issue. I tried the nightly build that you referenced, and now receive a new error: Argument types do not match. The result still returns okay when this property isn't expanded, however the error arises now whenever I request expansion on that property, even if I only filter to return records that have a value set for the optional navigation.
> 
> ** Stack Trace** System.ArgumentException: Argument types do not match at System.Linq.Expressions.Expression.Condition(Expression test, Expression ifTrue, Expression ifFalse) at Microsoft.AspNetCore.OData.Query.Expressions.SelectExpandBinder.RemoveNonStructucalProperties(QueryBinderContext context, Expression source, IEdmStructuredType structuredType) at Microsoft.AspNetCore.OData.Query.Expressions.SelectExpandBinder.ProjectElement(QueryBinderContext context, Expression source, SelectExpandClause selectExpandClause, IEdmStructuredType structuredType, IEdmNavigationSource navigationSource) at Microsoft.AspNetCore.OData.Query.Expressions.SelectExpandBinder.BindSelectExpand(SelectExpandClause selectExpandClause, QueryBinderContext context) at Microsoft.AspNetCore.OData.Query.Expressions.BinderExtensions.ApplyBind(ISelectExpandBinder binder, IQueryable source, SelectExpandClause selectExpandClause, QueryBinderContext context) at Microsoft.AspNetCore.OData.Query.SelectExpandQueryOption.ApplyTo(IQueryable queryable, ODataQuerySettings settings) at Microsoft.AspNetCore.OData.Query.ODataQueryOptions.ApplySelectExpand[T](T entity, ODataQuerySettings querySettings) at Microsoft.AspNetCore.OData.Query.ODataQueryOptions.ApplyTo(IQueryable query, ODataQuerySettings querySettings) at Microsoft.AspNetCore.OData.Query.EnableQueryAttribute.ApplyQuery(IQueryable queryable, ODataQueryOptions queryOptions) at Microsoft.AspNetCore.OData.Query.EnableQueryAttribute.ExecuteQuery(Object responseValue, IQueryable singleResultCollection, ControllerActionDescriptor actionDescriptor, HttpRequest request) at Microsoft.AspNetCore.OData.Query.EnableQueryAttribute.OnActionExecuted(ActionExecutedContext actionExecutedContext, Object responseValue, IQueryable singleResultCollection, ControllerActionDescriptor actionDescriptor, HttpRequest request) at Microsoft.AspNetCore.OData.Query.EnableQueryAttribute.OnActionExecuted(ActionExecutedContext actionExecutedContext) at Microsoft.AspNetCore.Mvc.Filters.ActionFilterAttribute.OnActionExecutionAsync(ActionExecutingContext context, ActionExecutionDelegate next) at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted) at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context) at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted) at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync() --- End of stack trace from previous location --- at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted) at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope) at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope) at Microsoft.AspNetCore.Routing.EndpointMiddleware.g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger) at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context) at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext) at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider) at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context) at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)

I hardcoded the nullable is "int?" So, It seems you have other nullable type?
Anyway, thanks for your trying. We will improve the codes.

**Comment by andy-clymer** [comment] 2023-08-31 02:18
> > > @andy-clymer @goatrodeosoftware can you try the nightly Microsoft.AspNetCore.OData 8.9.0-Nightly202308302217
> > 
> > 
> > @xuzhg Thanks for the quick response and action on this issue. I tried the nightly build that you referenced, and now receive a new error: Argument types do not match. The result still returns okay when this property isn't expanded, however the error arises now whenever I request expansion on that property, even if I only filter to return records that have a value set for the optional navigation.
> > ** Stack Trace** System.ArgumentException: Argument types do not match at System.Linq.Expressions.Expression.Condition(Expression test, Expression ifTrue, Expression ifFalse) at Microsoft.AspNetCore.OData.Query.Expressions.SelectExpandBinder.RemoveNonStructucalProperties(QueryBinderContext context, Expression source, IEdmStructuredType structuredType) at Microsoft.AspNetCore.OData.Query.Expressions.SelectExpandBinder.ProjectElement(QueryBinderContext context, Expression source, SelectExpandClause selectExpandClause, IEdmStructuredType structuredType, IEdmNavigationSource navigationSource) at Microsoft.AspNetCore.OData.Query.Expressions.SelectExpandBinder.BindSelectExpand(SelectExpandClause selectExpandClause, QueryBinderContext context) at Microsoft.AspNetCore.OData.Query.Expressions.BinderExtensions.ApplyBind(ISelectExpandBinder binder, IQueryable source, SelectExpandClause selectExpandClause, QueryBinderContext context) at Microsoft.AspNetCore.OData.Query.SelectExpandQueryOption.ApplyTo(IQueryable queryable, ODataQuerySettings settings) at Microsoft.AspNetCore.OData.Query.ODataQueryOptions.ApplySelectExpand[T](T entity, ODataQuerySettings querySettings) at Microsoft.AspNetCore.OData.Query.ODataQueryOptions.ApplyTo(IQueryable query, ODataQuerySettings querySettings) at Microsoft.AspNetCore.OData.Query.EnableQueryAttribute.ApplyQuery(IQueryable queryable, ODataQueryOptions queryOptions) at Microsoft.AspNetCore.OData.Query.EnableQueryAttribute.ExecuteQuery(Object responseValue, IQueryable singleResultCollection, ControllerActionDescriptor actionDescriptor, HttpRequest request) at Microsoft.AspNetCore.OData.Query.EnableQueryAttribute.OnActionExecuted(ActionExecutedContext actionExecutedContext, Object responseValue, IQueryable singleResultCollection, ControllerActionDescriptor actionDescriptor, HttpRequest request) at Microsoft.AspNetCore.OData.Query.EnableQueryAttribute.OnActionExecuted(ActionExecutedContext actionExecutedContext) at Microsoft.AspNetCore.Mvc.Filters.ActionFilterAttribute.OnActionExecutionAsync(ActionExecutingContext context, ActionExecutionDelegate next) at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted) at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context) at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted) at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync() --- End of stack trace from previous location --- at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted) at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope) at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope) at Microsoft.AspNetCore.Routing.EndpointMiddleware.g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger) at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context) at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext) at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider) at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context) at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
> 
> I hardcoded the nullable is "int?" So, It seems you have other nullable type? Anyway, thanks for your trying. We will improve the codes.

That's correct, we use "Guid?" as our foreign key.

**Comment by xuzhg** [comment] 2023-09-06 06:40
@andy-clymer @goatrodeosoftware would you please try the 8.2.3 and let us know any result? Thanks.

**Comment by andy-clymer** [comment] 2023-09-06 13:08
@xuzhg everything is working correctly now. Thank you.

**Comment by xuzhg** [comment] 2023-09-06 16:39
@andy-clymer Thanks for your information. Let me close this issue and please file any new issue if you have more questions/concerns.

**Closed by xuzhg** 2023-09-06 16:39 UTC
Labels: bug, regression

**Comment by goranhrovat** [comment] 2024-05-31 14:21
in 8.2.5 is broken again
