### ISSUE TITLE
how custom serialize rule in odata? i want to convert long to string  and convert enum to int

### ISSUE THREAD

**Issue by ClementeGao** [OData/AspNetCoreOData#274] opened 2021-08-15 16:03 UTC

**Comment by xuzhg** [comment] 2021-08-17 23:44
Long to string is controlled by "IsIeee754Compatible "

Would you please share more detailed requirements?

**Comment by ClementeGao** [comment] 2021-08-18 14:03
@xuzhg Because the long type will drop frames in JS，so i want to unified processing it and Enum type displays the name in JS instead of its value, such as enum Status{
 Open = 1,
Close = 2
}
But on the js side, the string open is displayed instead of 1.

**Comment by xuzhg** [comment] 2021-08-18 17:09
@ClementeGao So, it could work if you customize the serializer. 
1) Create a class derived from "ODataResourceSerializer", override certain methods 
2) Create a class derived from "ODataSerializerProvider", override methods, for entity, return your own "resource serializer", others call base method.
3) Register provider when call "AddRouteComponent".

**Comment by xuzhg** [comment] 2021-08-18 18:04
@ClementeGao By the way, use  'IEEE754Compatible=false/true' in $format or Accept header can return the long value as string.

**Comment by KenitoInc** [comment] 2022-04-14 08:55
@ClementeGao 
Was you issues resolved? If yes, we can close this issue

**Comment by paule96** [comment] 2022-09-12 06:24
@xuzhg, I don't get the format url or header to work. I tried first the URL format parameter like:

```
$format=application/json;IEEE754Compatible=true
```

And then I set the also the accept header explicitly like:

```
Accept: application/json;IEEE754Compatible=true
```

but both didn't work.
So it is still a must to write your own `ODataResourceSerializer`?

**Comment by paule96** [comment] 2022-09-14 13:27
Now I implemented my own `ODataResourceSerializer` like that:

```csharp
    internal class EnumSerializer : ODataResourceSerializer
    {
        public EnumSerializer(IODataSerializerProvider serializerProvider) : base(serializerProvider)
        {
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="graph">This is the value that odata would set normaly</param>
        /// <param name="expectedType"></param>
        /// <param name="writeContext"></param>
        /// <returns></returns>
        public override ODataValue CreateODataValue(object graph, IEdmTypeReference expectedType, ODataSerializerContext writeContext)
        {

            if (!expectedType.IsEnum())
            {
                throw new ArgumentException("The enum serializer can only be used for enums.");
            }
            if (
                writeContext.Request.Query["$format"].Any(f => f.Contains("IEEE754Compatible=true")) ||
                (
                    // The query parameter is more important then the header.
                    // So only if the query parameter isn't set we read the header.
                    // http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionformat
                    !writeContext.Request.Query["$format"].Any(f => f.Contains("IEEE754Compatible=")) &&
                    writeContext.Request.Headers.Accept.Contains("IEEE754Compatible=true")
                )
            )
            {
                //expectedType.AsEnum().
                long enumNumberValue = expectedType.AsEnum().EnumDefinition()
                    .Members.Where(m => m.Name == graph.ToString()).First().Value.Value;
                return new ODataPrimitiveValue(enumNumberValue);
            }
            return new ODataEnumValue(graph.ToString());
            //return base.CreateODataValue(graph, expectedType, writeContext);
        }
    }
```

Now the problem is, that I get the following error if this convert is running:

```
-------- Microsoft.OData.ODataException : A primitive value was specified; however, a value of the non-primitive type 'XXX.Internal.AspNetCore.GenericOData.Tests.Models.GameType' was expected.
```

Because it requires an enum to return and not a long or int.

is there any advice here @xuzhg how to solve the diffrent return types? I guess I can say to the `writeContext` somehow, that I want change the return type.

**Closed** 2023-12-18 09:09 UTC
Labels: followup, investigated
