### ISSUE TITLE
ODataUriResolver.EnableCaseInsensitive is false 

### ISSUE THREAD

**Issue by MichalWeczorek** [OData/AspNetCoreOData#1312] opened 2024-09-10 17:56 UTC
**Assemblies affected**
ASP.NET Core OData 9.x

**Describe the bug**
Odata Query for expand Query is case sensitive 

call the OData Controller with 
GET https://localhost:54001/odata/Books?$expand=authors
```
*error*
"error": {
    "code": "",
    "message": "The query specified in the URI is not valid. Could not find a property named 'authors' on type 'xxx.BooksDto'.",
    "details": [],
    "innererror": {
      "message": "Could not find a property named 'authors' on type 'xxxxx'.",
      "type": "Microsoft.OData.ODataException",
      "stacktrace": "   at Microsoft.OData.UriParser.SelectExpandBinder.GenerateExpandItem(ExpandTermToken tokenIn)\r\n   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()\r\n   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()\r\n   at System.Collections.Generic.List`1.AddRange(IEnumerable`1 collection)\r\n   at Microsoft.OData.UriParser.SelectExpandBinder.Bind(ExpandToken expandToken, SelectToken selectToken)\r\n   at Microsoft.OData.UriParser.SelectExpandSemanticBinder.Bind(ODataPathInfo odataPathInfo, ExpandToken expandToken, SelectToken selectToken, ODataUriParserConfiguration configuration, BindingState state)\r\n   at Microsoft.OData.UriParser.ODataQueryOptionParser.ParseSelectAndExpandImplementation(String select, String expand, ODataUriParserConfiguration configuration, ODataPathInfo odataPathInfo)\r\n   at Microsoft.OData.UriParser.ODataQueryOptionParser.ParseSelectAndExpand()\r\n   at Microsoft.AspNetCore.OData.Query.SelectExpandQueryOption.get_SelectExpandClause()\r\n   at Microsoft.AspNetCore.OData.Query.Validator.SelectExpandQueryValidator.Validate(SelectExpandQueryOption selectExpandQueryOption, ODataValidationSettings validationSettings)\r\n   at Microsoft.AspNetCore.OData.Query.SelectExpandQueryOption.Validate(ODataValidationSettings validationSettings)\r\n   at Microsoft.AspNetCore.OData.Query.Validator.ODataQueryValidator.Validate(ODataQueryOptions options, ODataValidationSettings validationSettings)\r\n   at Microsoft.AspNetCore.OData.Query.ODataQueryOptions.Validate(ODataValidationSettings validationSettings)\r\n   at Microsoft.AspNetCore.OData.Query.EnableQueryAttribute.ValidateQuery(HttpRequest request, ODataQueryOptions queryOptions)\r\n   at Microsoft.AspNetCore.OData.Query.EnableQueryAttribute.OnActionExecuting(ActionExecutingContext actionExecutingContext)"
    }
```

ODataUriResolver.EnableCaseInsensitive is set to false 
it should be true 

**workaround**
```
 options.AddRouteComponents(routePrefix, model, services =>
        {
  services.AddDefaultODataServices(
                    odataVersion: ODataVersion.V4,
                    configureReaderAction: settings =>
                    {
                       settings.LibraryCompatibility |=
                             ODataLibraryCompatibility.Version7;
                    },
                    configureWriterAction: settings =>
                    {
                        
                                          settings.LibraryCompatibility |=
                             ODataLibraryCompatibility.Version7;
                    },
                    configureUriParserAction: settings =>
                    {
                        settings.MaximumExpansionCount = 10;
         
                    }
                );
 services.AddSingleton<ODataUriResolver>(_ => new ODataUriResolver() { EnableCaseInsensitive = true });
}
```
Thanks

**Comment by julealgon** [comment] 2024-09-10 18:07
@MichalWeczorek can you elaborate what you are using as the basis to affirm that `ODataUriResolver.EnableCaseInsensitive` should be `true` or that "Odata Query for expand Query is case sensitive"?

**Comment by julealgon** [comment] 2024-09-10 18:27
I see, so this is a regression then. Thanks for clarifying @MichalWeczorek !

**Comment by xuzhg** [comment] 2024-09-11 18:03
It's weird because we didn't change the configuration in 9.x. See: https://github.com/OData/AspNetCoreOData/blob/main/src/Microsoft.AspNetCore.OData/ODataOptions.cs#L329

Do you use the 'OData EdmModel' in your scenario (or do you call AddRouteComponents(...))?

**Comment by gathogojr** [comment] 2024-09-19 06:29
I build a simple project to repro the issue:

### Data models
```csharp
namespace Repro.Models
{
    public class Book
    {
        public int Id { get; set; }
        public required string Title { get; set; }
        public List<Author>? Authors { get; set; }
    }

    public class Author
    {
        public int Id { get; set; }
        public required string Name { get; set; }
    }
}
```

### Controller
```csharp
using Ex312.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.OData.Query;
using Microsoft.AspNetCore.OData.Results;
using Microsoft.AspNetCore.OData.Routing.Controllers;

namespace Repro.Controllers
{
    public class BooksController : ODataController
    {
        private List<Book> books = new List<Book>
        {
            new Book
            {
                Id = 1,
                Title = "A Song of Ice and Fire",
                Authors = new List<Author>
                {
                    new Author
                    {
                        Id = 1,
                        Name = "George R. R. Martin"
                    }
                }
            },
            new Book
            {
                Id = 2,
                Title = "The Chronicles of Narnia",
                Authors = new List<Author>
                {
                    new Author
                    {
                        Id = 2,
                        Name = "C. S. Lewis"
                    }
                }
            },
            new Book
            {
                Id = 3,
                Title = "Harry Porter",
                Authors = new List<Author>
                {
                    new Author
                    {
                        Id = 3,
                        Name = "J. K. Rowling"
                    }
                }
            }
        };

        [EnableQuery]
        public ActionResult<IEnumerable<Book>> Get()
        {
            return books;
        }

        [EnableQuery]
        public SingleResult<Book> Get(int key)
        {
            return SingleResult.Create(books.AsQueryable().Where(d => d.Id == key));
        }
    }
}
```

The issue is not reproducible if you configure the service as follows:
```csharp
using Repro.Models;
using Microsoft.AspNetCore.OData;
using Microsoft.OData;
using Microsoft.OData.ModelBuilder;

var builder = WebApplication.CreateBuilder(args);

var modelBuilder = new ODataConventionModelBuilder();
modelBuilder.EntitySet<Book>("Books");

builder.Services.AddControllers().AddOData(
    options => options.EnableQueryFeatures().AddRouteComponents(
        modelBuilder.GetEdmModel()));

var app = builder.Build();

app.UseRouting();
app.MapControllers();

app.Run();
```

But it's reproducible if you call `AddDefaultODataServices` from your service configuration logic as follows:
```csharp
using Ex312.Models;
using Microsoft.AspNetCore.OData;
using Microsoft.OData;
using Microsoft.OData.ModelBuilder;

var builder = WebApplication.CreateBuilder(args);

var modelBuilder = new ODataConventionModelBuilder();
modelBuilder.EntitySet<Book>("Books");

builder.Services.AddControllers().AddOData(
    options => options.EnableQueryFeatures().AddRouteComponents(
        routePrefix: string.Empty,
        model: modelBuilder.GetEdmModel(),
        configureServices: (services) =>
        {
            services.AddDefaultODataServices(
                odataVersion: ODataVersion.V4,
                configureReaderAction: (settings) => settings.LibraryCompatibility |= ODataLibraryCompatibility.Version7,
                configureWriterAction: (settings) => settings.LibraryCompatibility |= ODataLibraryCompatibility.Version7,
                configureUriParserAction: (settings) => settings.MaximumExpansionDepth = 10);
        }));

var app = builder.Build();

app.UseRouting();
app.MapControllers();

app.Run();
```

The issue is more likely in ODL. I'll tag this as a P1 since it's a regression that should be fixed urgently.

cc. @xuzhg

**Comment by gathogojr** [comment] 2024-09-19 07:50
**UPDATE:**
No change is required actually.

When a user decides to call `AddODataDefaultServices` from their service configuration logic, they should be aware that it might lead to services that were injected by the `AddRouteComponents` method in ASP.NET Core OData being overridden with "default" services that ODL configures. One of those services is the `ODataUriResolver` that is configured to be case insensitive in ASP.NET Core OData:
https://github.com/OData/AspNetCoreOData/blob/1368836752963d88e920d9508d94807eb995894b/src/Microsoft.AspNetCore.OData/ODataOptions.cs#L326-L329

However, in ODL, the `ODataUriResolver` that is configured has `EnableCaseInsensitive` defaulting to `false`:
https://github.com/OData/odata.net/blob/95233fc8a399cbae6e816216528d02a581b77b48/src/Microsoft.OData.Core/ODataServiceCollectionExtensions.cs#L49

This is the reason for the behaviour observed here.

By calling the `AddRouteComponents` overloads that accepts the `configureServices` `Action<IServiceCollection>` parameter, the developer is taking the responsibility of ensuring that the right services are configured with the desired settings.

I'll however propose defaulting `EnableCaseInsensitive` to true when initializing a new instance of `ODataUriResolver` in ODL. This would happen in the next major release to avoid breaking customers.

**Closed by gathogojr** 2024-09-19 07:50 UTC
Labels: bug, investigating
