### ISSUE TITLE
$metadata 404 endpoint not found in version 8.0.7 worked in 8.0.6

### ISSUE THREAD

**Issue by starsoftnl** [OData/AspNetCoreOData#493] opened 2022-02-18 12:53 UTC
Starting with version 8.0.7 i get a 404 not found error for the $metadata endpoint.

**Comment by xuzhg** [comment] 2022-02-18 18:05
@starsoftnl Can you share more details? Or Can you share with me a reproduction?

**Comment by starsoftnl** [comment] 2022-02-22 13:02
I just tested with version 8.0.8 and now it works

**Comment by habbes** [comment] 2022-02-22 16:51
Thanks @starsoftnl. I'm closing this issue since it has been resolved.

**Closed by habbes** 2022-02-22 16:51 UTC
