### ISSUE TITLE
Oracle EF EDM controller

### ISSUE THREAD

**Issue by yongkeecho** [OData/AspNetCoreOData#387] opened 2021-11-19 23:07 UTC
Following [ODataRoutingSample](https://github.com/OData/AspNetCoreOData/tree/master/sample/ODataRoutingSample) using Oracle EF as data context, endpoints for two routes are always mapped the same. How can I make Experiments({id}) or Experiments/{id} endpoints?
```
        [HttpGet]
        [EnableQuery]
        public IActionResult Get()
        {
            return Ok(_context.Experiments);
        }

        [EnableQuery]
        [HttpGet]
        public IActionResult Get(int id)
        {
            var experiment = _context.Experiments.Find(id);
            if (experiment == null) return NotFound();
            return Ok(experiment);
        }
```

Controller   & Action | HttpMethods | Template
-- | -- | --
MyApp.Controllers.ExperimentsController.Get   (MyApp) | GET | Experiments
MyApp.Controllers.ExperimentsController.Get   (MyApp) | GET | Experiments/$count
MyApp.Controllers.ExperimentsController.Get   (MyApp) | GET | Experiments
MyApp.Controllers.ExperimentsController.Get   (MyApp) | GET | Experiments/$count
Microsoft.AspNetCore.OData.Routing.Controllers.MetadataController.GetMetadata   (Microsoft.AspNetCore.OData) | GET | $metadata
Microsoft.AspNetCore.OData.Routing.Controllers.MetadataController.GetServiceDocument   (Microsoft.AspNetCore.OData) | GET |

**Comment by xuzhg** [comment] 2021-11-22 22:39
@yongkeecho Rename "int id" to "int key"

**Comment by xuzhg** [comment] 2021-11-23 19:16
@yongkeecho By conventional rule, "key" is the name by design. We consider adding "id" into the conventional rule, so far it hasn't been merged. 

if you do want to use "id", you can change it using attribute routing.

```C#
[EnableQuery]
[HttpGet("/prefix/Experiments/{id}"]
public IActionResult GetById(int id)
{
   var experiment = _context.Experiments.Find(id);
   if (experiment == null) return NotFound();
   return Ok(experiment);
}
```

**Comment by yongkeecho** [comment] 2021-11-23 21:06
Key works like a charm. @xuzhg Thank you for your quick response!

**Closed** 2021-11-23 21:12 UTC
Labels: followup, investigated
