### ISSUE TITLE
Skiptoken fails to generate on second page query when using orderby desc

### ISSUE THREAD

**Issue by jsangco** [OData/AspNetCoreOData#1068] opened 2023-10-07 07:51 UTC
Using Microsoft.AspNetCore.OData version 8.2.3, the framework will properly generate the `skiptoken` for the first API call, but it fails to generate a `nextLink` on subsequent calls when using a `orderby=id desc` query.

Here is an example of the output I see when executing the following queries with a max page size of 3 and 100 `customers`
```
> curl https://localhost:7187/odata/customers?orderby=id%20desc
{
  "value": [{"id": 100},{"id": 99},{"id": 98}],
  "@odata.nextLink": "https://localhost:7187/odata/customers?orderby=id%20desc&$skiptoken=id-97"
}

> curl https://localhost:7187/odata/customers?orderby=id%20desc&$skiptoken=id-97
{
  "value": [{"id": 97},{"id": 96},{"id": 95}],
}
```
> Note: The second query does not contain the `@odata.nextLink` property.

This query was working in version 8.0.11, however, in that version, `skipToken` does not work with `select` queries.
Please advise.

**Comment by gathogojr** [comment] 2023-10-09 09:41
@jsangco Closing this as a duplicate of https://github.com/OData/AspNetCoreOData/issues/1061. Review the feedback on the other issue where an attempt to reproduce the issue was unsuccessful https://github.com/OData/AspNetCoreOData/issues/1061#issuecomment-1744245450

**Closed by gathogojr** 2023-10-09 09:41 UTC
Labels: bug
