### ISSUE TITLE
[JsonIgnore] attribute ignored when using $expand

### ISSUE THREAD

**Issue by mattperdeck** [OData/AspNetCoreOData#727] opened 2022-10-26 02:37 UTC
My API end points look like this:
```
        [HttpGet("List")]
        [EnableQuery]
        public override ActionResult<IQueryable<ApiScopeListV>> List()
        {
		    ....
            return query;
        }
```
The view models use JsonProperty attributes to rename JSON response fields, and JsonIgnore attributes to ensure some fields are not sent in the JSON response:
```
    public partial class ApiScopeListV
    {
        [JsonProperty("ScopeId")]
        public Guid ExternalId { get; set; }

        [JsonIgnore]
        public int Id { get; set; }

        [StringLength(250)]
        public string ScopeName { get; set; }

        [Column(TypeName = "money")]
        public decimal? ScopeLocalDiscount { get; set; }

        ....
    }
```
This works as expected as long as I don't use $expand in my OData queries. 

However, when I use $expand, the JsonProperty attributes are still honoured, but the JsonIgnore attributes are ignored. 

So with the ApiScopeListV objects above, without using $expand, the Id field is not present in the JSON response (as expected). But with $expand, that Id field does appear in the JSON response (not expected).

This bug happens both when using [Newtonsoft.Json.JsonIgnore] and [System.Text.Json.Serialization.JsonIgnore]. When trying [Newtonsoft.Json.JsonIgnore], I used AddODataNewtonsoftJson during startup to tell OData to use Newtonsoft.Json.

This same problem is referred to by @gordon-matt in 
https://github.com/OData/AspNetCoreOData/issues/424#issuecomment-1009565102

**Comment by julealgon** [comment] 2022-10-26 12:30
Can you provide full sample payloads with and without expansion for reference?

**Comment by mattperdeck** [comment] 2022-10-27 03:13
I just created a pull request to fix this issue: https://github.com/OData/AspNetCoreOData/pull/728

To answer your question, below I included:

- Response using $expand
- Response when not using $expand
- Versions of the OData library used
- EF model for parent item ApiInitiativeListV (including [JsonIgnore] attributes)
- EF model for child item ApiDeliverableListV (including [JsonIgnore] attributes)

==============================================================================
Response using $expand, with url
https://localhost/PublicApi/v1/Initiative/List?$top=5&$expand=Deliverables

Note presence of fields Id, InternalScopeId, InternalScopeId, etc.
```
[
    {
        "Deliverables": [],
        "InitiativeId": "a42b7982-22fe-4d5a-ab91-2b405f6e5580",
        "Id": 3112,
        "OriginalInitiativeId": "a42b7982-22fe-4d5a-ab91-2b405f6e5580",
        "ScopeId": "e6674ef8-4811-42b8-96dd-1f9c0b4f06cc",
        "InternalScopeId": 1791,
        "InternalClientId": 1018,
        "InitiativeOrder": 1,
        "InitiativeName": "General",
        "InitiativeMasterOrder": null,
        "InitiativeMasterName": null,
        "DateCreated": "2019-04-05T11:54:50.193",
        "DateLastUpdated": null
    },
    {
        "Deliverables": [],
        "InitiativeId": "47147c07-5bc4-40cb-90a5-1d997fbcba87",
        "Id": 3153,
        "OriginalInitiativeId": "47147c07-5bc4-40cb-90a5-1d997fbcba87",
        "ScopeId": "32e78a55-9435-4043-8f3a-7c02897a2599",
        "InternalScopeId": 31631,
        "InternalClientId": 1018,
        "InitiativeOrder": 1,
        "InitiativeName": "General",
        "InitiativeMasterOrder": null,
        "InitiativeMasterName": null,
        "DateCreated": "2019-10-22T10:18:29.53",
        "DateLastUpdated": null
    },
    {
        "Deliverables": [
            {
                "DeliverableId": "6d8db36b-054b-47d0-8303-cbb937d810bb",
                "Id": 3079,
                "OriginalDeliverableId": "6d8db36b-054b-47d0-8303-cbb937d810bb",
                "InternalOriginalDeliverableId": 3079,
                "InitiativeId": "19dd6276-7d5c-43b8-a203-a72dbfe743d3",
                "InternalInitiativeId": 3154,
                "ScopeId": "28a371a0-cbc7-4ed2-bf70-05465d312426",
                "InternalScopeId": 31632,
                "InternalClientId": 1018,
                "DeliverableOrder": 1,
                "DeliverableName": "Business, Internet Site",
                "DeliverableTypeId": "d329f110-ac68-435e-86b6-295939068251",
                "DeliverableTypeOrder": 9,
                "DeliverableTypeName": "Internet Site",
                "DeliverableQuantity": 22.00,
                "DeliverableTimeframe": null,
                "DeliverableEstimatedFee": null,
                "DeliverableIsFixedFee": false,
                "DeliverableRequiresProduction": false,
                "DeliverableProbableProductionYear": null,
                "DeliverableProbableProductionMonth": null,
                "DateCreated": "2019-10-22T10:24:26.873",
                "DateLastUpdated": "2019-10-22T10:29:28.48"
            }
        ],
        "InitiativeId": "19dd6276-7d5c-43b8-a203-a72dbfe743d3",
        "Id": 3154,
        "OriginalInitiativeId": "47147c07-5bc4-40cb-90a5-1d997fbcba87",
        "ScopeId": "28a371a0-cbc7-4ed2-bf70-05465d312426",
        "InternalScopeId": 31632,
        "InternalClientId": 1018,
        "InitiativeOrder": 1,
        "InitiativeName": "General",
        "InitiativeMasterOrder": null,
        "InitiativeMasterName": null,
        "DateCreated": "2019-10-22T10:19:17.54",
        "DateLastUpdated": null
    },
    {
        "Deliverables": [],
        "InitiativeId": "21898733-f5cc-47f3-b075-11f9f3dc33e7",
        "Id": 3155,
        "OriginalInitiativeId": "21898733-f5cc-47f3-b075-11f9f3dc33e7",
        "ScopeId": "28a371a0-cbc7-4ed2-bf70-05465d312426",
        "InternalScopeId": 31632,
        "InternalClientId": 1018,
        "InitiativeOrder": 2,
        "InitiativeName": "lets go out",
        "InitiativeMasterOrder": null,
        "InitiativeMasterName": null,
        "DateCreated": "2019-10-22T10:24:40.953",
        "DateLastUpdated": null
    },
    {
        "Deliverables": [],
        "InitiativeId": "35fbd9f8-d524-42fd-b605-3c83c23ee128",
        "Id": 3156,
        "OriginalInitiativeId": "35fbd9f8-d524-42fd-b605-3c83c23ee128",
        "ScopeId": "a274e263-787b-4e8c-a515-0bf67d81aa61",
        "InternalScopeId": 31633,
        "InternalClientId": 1018,
        "InitiativeOrder": 1,
        "InitiativeName": "General",
        "InitiativeMasterOrder": null,
        "InitiativeMasterName": null,
        "DateCreated": "2019-10-28T10:40:42.29",
        "DateLastUpdated": null
    }
]
```

===================================================================
Response when not using $expand, using url
https://localhost/PublicApi/v1/Initiative/List?$top=5

Note absence of fields Id, InternalScopeId, InternalScopeId, etc.

```
[
    {
        "Deliverables": [],
        "MediaBuys": [],
        "Expenses": [],
        "ScopeFees": [],
        "InitiativeId": "a42b7982-22fe-4d5a-ab91-2b405f6e5580",
        "OriginalInitiativeId": "a42b7982-22fe-4d5a-ab91-2b405f6e5580",
        "ScopeId": "e6674ef8-4811-42b8-96dd-1f9c0b4f06cc",
        "InitiativeOrder": 1,
        "InitiativeName": "General",
        "InitiativeMasterOrder": null,
        "InitiativeMasterName": null,
        "DateCreated": "2019-04-05T11:54:50.193",
        "DateLastUpdated": null
    },
    {
        "Deliverables": [],
        "MediaBuys": [],
        "Expenses": [],
        "ScopeFees": [],
        "InitiativeId": "47147c07-5bc4-40cb-90a5-1d997fbcba87",
        "OriginalInitiativeId": "47147c07-5bc4-40cb-90a5-1d997fbcba87",
        "ScopeId": "32e78a55-9435-4043-8f3a-7c02897a2599",
        "InitiativeOrder": 1,
        "InitiativeName": "General",
        "InitiativeMasterOrder": null,
        "InitiativeMasterName": null,
        "DateCreated": "2019-10-22T10:18:29.53",
        "DateLastUpdated": null
    },
    {
        "Deliverables": [],
        "MediaBuys": [],
        "Expenses": [],
        "ScopeFees": [],
        "InitiativeId": "19dd6276-7d5c-43b8-a203-a72dbfe743d3",
        "OriginalInitiativeId": "47147c07-5bc4-40cb-90a5-1d997fbcba87",
        "ScopeId": "28a371a0-cbc7-4ed2-bf70-05465d312426",
        "InitiativeOrder": 1,
        "InitiativeName": "General",
        "InitiativeMasterOrder": null,
        "InitiativeMasterName": null,
        "DateCreated": "2019-10-22T10:19:17.54",
        "DateLastUpdated": null
    },
    {
        "Deliverables": [],
        "MediaBuys": [],
        "Expenses": [],
        "ScopeFees": [],
        "InitiativeId": "21898733-f5cc-47f3-b075-11f9f3dc33e7",
        "OriginalInitiativeId": "21898733-f5cc-47f3-b075-11f9f3dc33e7",
        "ScopeId": "28a371a0-cbc7-4ed2-bf70-05465d312426",
        "InitiativeOrder": 2,
        "InitiativeName": "lets go out",
        "InitiativeMasterOrder": null,
        "InitiativeMasterName": null,
        "DateCreated": "2019-10-22T10:24:40.953",
        "DateLastUpdated": null
    },
    {
        "Deliverables": [],
        "MediaBuys": [],
        "Expenses": [],
        "ScopeFees": [],
        "InitiativeId": "35fbd9f8-d524-42fd-b605-3c83c23ee128",
        "OriginalInitiativeId": "35fbd9f8-d524-42fd-b605-3c83c23ee128",
        "ScopeId": "a274e263-787b-4e8c-a515-0bf67d81aa61",
        "InitiativeOrder": 1,
        "InitiativeName": "General",
        "InitiativeMasterOrder": null,
        "InitiativeMasterName": null,
        "DateCreated": "2019-10-28T10:40:42.29",
        "DateLastUpdated": null
    }
]
```

==================================================
Versions of the OData library used

```
		<PackageReference Include="Microsoft.AspNetCore.OData" Version="8.0.11" />
		<PackageReference Include="Microsoft.AspNetCore.OData.NewtonsoftJson" Version="8.0.4" />
```

=================================================================================
EF model for parent item ApiInitiativeListV
Note items marked [JsonIgnore], such as Id and InternalClientId

```
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Decideware.Data
{
    [Table("API_InitiativeList_v")]
    public partial class ApiInitiativeListV
    {
        [JsonProperty("InitiativeId")]
        public Guid ExternalId { get; set; }

        [JsonIgnore]
        public int Id { get; set; }

        public Guid OriginalInitiativeId { get; set; }

        public Guid ScopeId { get; set; }
        [JsonIgnore]
        public int InternalScopeId { get; set; }

        [JsonIgnore]
        public int InternalClientId { get; set; }

        public int InitiativeOrder { get; set; }

        [StringLength(150)]
        public string InitiativeName { get; set; }

        public int? InitiativeMasterOrder { get; set; }

        [StringLength(100)]
        public string InitiativeMasterName { get; set; }

        [Column(TypeName = "datetime")]
        public DateTime DateCreated { get; set; }

        [Column(TypeName = "datetime")]
        public DateTime? DateLastUpdated { get; set; }

    }
}
```

=================================================================================
EF model for child item ApiDeliverableListV
Note items marked [JsonIgnore], such as Id, InternalInitiativeId and InternalClientId

```
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Decideware.Data
{
    [Table("API_DeliverableList_v")]
    public partial class ApiDeliverableListV
    {
        [JsonProperty("DeliverableId")]
        public Guid ExternalId { get; set; }

        [JsonIgnore]
        public int Id { get; set; }

        public Guid OriginalDeliverableId { get; set; }
        [JsonIgnore]
        public int InternalOriginalDeliverableId { get; set; }
        public Guid InitiativeId { get; set; }
        [JsonIgnore]
        public int InternalInitiativeId { get; set; }
        public Guid ScopeId { get; set; }
        [JsonIgnore]
        public int InternalScopeId { get; set; }

        [JsonIgnore]
        public int InternalClientId { get; set; }

        public int DeliverableOrder { get; set; }

        [StringLength(150)]
        public string DeliverableName { get; set; }

        public Guid DeliverableTypeId { get; set; }

        public int DeliverableTypeOrder { get; set; }

        [StringLength(200)]
        public string DeliverableTypeName { get; set; }

        [Column(TypeName = "decimal(8, 2)")]
        public decimal DeliverableQuantity { get; set; }

        [StringLength(150)]
        public string DeliverableTimeframe { get; set; }

        [StringLength(150)]
        public string DeliverableEstimatedFee { get; set; }

        public bool? DeliverableIsFixedFee { get; set; }

        public bool? DeliverableRequiresProduction { get; set; }

        public int? DeliverableProbableProductionYear { get; set; }

        public int? DeliverableProbableProductionMonth { get; set; }

        [Column(TypeName = "datetime")]
        public DateTime DateCreated { get; set; }

        [Column(TypeName = "datetime")]
        public DateTime? DateLastUpdated { get; set; }

    }
}
```

**Comment by stevendarby** [comment] 2022-10-27 07:46
Try `[IgnoreDataMember]` which excludes it from the OData model, excludes it from the expand scenario, as well as preventing serialisation in the non-expand scenario.

**Comment by stevendarby** [comment] 2022-10-27 07:48
Duplicate of https://github.com/OData/WebApi/issues/2462

**Comment by julealgon** [comment] 2022-10-27 16:46
> To answer your question, below I included:
> 
> * Response using $expand
> * Response when not using $expand

@mattperdeck , those payloads are clearly not OData payloads, but raw standard MVC payloads instead. Are you using [EnableQuery] with a standard MVC endpoint? If not, can you please share your controller and EDM model generation logic?

If your intent was for these to be full OData APIs, you clearly have a problem right now since your endpoint is not being detected as an OData endpoint.

You can use the output from the `$odata` debug middleware to double check whether your routes are being properly detected as OData or not.

**Comment by mattperdeck** [comment] 2022-10-28 00:39
Tried using [IgnoreDataMember] instead of [JsonIgnore] in my view model, and found that it does the trick. Fields with that attribute do not get included in the output, both when using $expand and when not using $expand. Thanks @stevendarby.

Still, would like to argue in favour of adding support for [JsonIgnore]:

- It's a land mine. Currently, [JsonIgnore] does work when not using $expand. A dev team could easily release code using [JsonIgnore] to hide sensitive info, thinking that this works because they only tested without $expand (sloppy, but realistic in my view). An outside user could then stumble upon the sensitive data by using $expand.
- Developers familiar with Newtonsoft.Json and System.Text.Json will naturally assume that [JsonIgnore] will do the job. Not least because [JsonProperty("....")] and  [JsonPropertyName("....")] always work (both with $expand and without $expand). 
- I am at least the 3rd developer writing a bug report for this issue. Guess there will be more in the future. Supporting [JsonIgnore] means your team no longer has to deal with these bug reports.
- I would never have guessed to try [IgnoreDataMember] if @stevendarby hadn't told me about it.
- My proposed solution for supporting [JsonIgnore] allows developers to use MapProperty not only to rename fields, but also to ignore them. https://github.com/OData/AspNetCoreOData/pull/728

**Comment by mattperdeck** [comment] 2022-10-28 01:01
@julealgon I am using [EnableQuery] with a mostly standard MVC endpoint. The one thing that is not standard about it is that it returns an _ActionResult<IQueryable<..>>_ (that is, a query) instead of say _ActionResult<List<..>>_

For example:
```
[HttpGet("List")]
[EnableQuery]
public override ActionResult<IQueryable<ApiScopeListV>> List()
{
    ....
    return query;
}
```
I noticed that in one example, an Edm model is used:
```
public void ConfigureServices(IServiceCollection services)
{
    services.AddControllers()
        .AddOData(opt => opt.Select().Filter().Count().SetMaxTop(10)
        .AddRouteComponents("odata", GetEdmModel()))     // <<<<<<<<<<
        .AddODataNewtonsoftJson();

     .......
 }
```
While my startup looks like this (no Edm model):
```
    public void ConfigureServices(IServiceCollection services)
    {
        ....
        services.AddControllers().AddOData(option => 
            option.Select().Filter().Count().OrderBy().Expand().SetMaxTop(maxNbrQueryResultsReturned))
            .AddODataNewtonsoftJson();
```

**Comment by julealgon** [comment] 2022-10-28 12:04
> @julealgon I am using [EnableQuery] with a mostly standard MVC endpoint. The one thing that is not standard about it is that it returns an _ActionResult<IQueryable<..>>_ (that is, a query) instead of say _ActionResult<List<..>>_
> ...
> I noticed that in one example, an Edm model is used:

Just keep in mind that you are not using "the full power" of OData this way. While there is support for EDM-less flow using `[EnableQuery]` like that, not every OData feature will work in that mode.

If you don't have any restrictions around it, I'd strongly recommend using a proper EDM model to back up your endpoints.

> Still, would like to argue in favour of adding support for [JsonIgnore]:

This is the main reason why the attribute does not work:
- https://github.com/OData/AspNetCoreOData/issues/477

IMHO, solutions other than just "use STJ/configured serializer as the serializer" would be considered workarounds/hacks.

What is happening in your example is that the standard MVC endpoint without expand relies on the normal serializer configured in the API (STJ by default), but as soon as you add the `$expand` clause, part of your model is serialized using custom OData serialization, which doesn't honor STJ attributes.

If you converted your endpoints to true OData endpoints (by introducing an EDM model), you'd start to see the same problem on every payload, as then everything gets serialized by OData.

Once OData adopts the configured API serializer, this issue goes away.

**Comment by stevendarby** [comment] 2022-10-28 12:39
Isn't the problem that the attribute is on your model but when using select/expand, it doesn't return that model, it uses a wrapper with a dictionary (because some properties might not have been selected etc). So it's not about what serialiser is used but whether the process or adding to that dictionary is aware of attributes like JsonIgnore etc

**Comment by mattperdeck** [comment] 2022-10-30 22:53
@stevendarby @julealgon
I think the two of you are both saying the same thing (with which I concur): When not using $expand, the standard serializer is used (the one for STJ or the one for NewtonSoft.Json), while when using $expand that standard serializer is not used and the OData library sets out to interpret attributes itself. And that it would be better if the standard serializer were used with $expand as well.

I guess that $expand doesn't use the standard serializer for some intricate reason. And that it will be non-trivial to get $expand to use the standard serializer. As in, it may never happen.

This is way I did the pull request https://github.com/OData/AspNetCoreOData/pull/728 to stop the bleeding. So at least JsonIgnore is supported, so it no longer fails silently for just $expand and reveal potentially sensitive information.

**Comment by stevendarby** [comment] 2022-10-30 23:11
No, I think in both cases whatever serialiser you have configured is used, but in the non-expand case it’s serialising your model (with JsonIgnore attributes) and in the expand case it’s essentially serialising a dictionary.

**Comment by habbes** [comment] 2022-11-08 04:59
@mattperdeck we had a discussion about this. We have not reached a consensus that supporting attributes specific to one or more JSON serializer is the best direction (cc @corranrogue9). As far as discoverability is concerned, my opinion is that better documentation can help make it clear what is and isn't supported. Using the standard serializer (by this I assume you're referring to System.Text.Json) to interpret $expand and other query options would be non-trivial. @corranrogue9 suggested that OData provides a set of attributes that are not dependent on other libraries or serializers. I tend to agree with that idea. However, this is still an open discussion.

Another thing to consider is that the OData model is format-agnostic. `[JsonIgnore]` is JSON-specific. Is the intention here that the target property be omitted from the JSON response, or omitted from the model/schema altogether?

**Comment by mattperdeck** [comment] 2022-11-08 05:16
As a developer, I just want to get my stuff done. Specifically in this case, ignore fields (so they are not included in the JSON response) and rename fields. the sole reason myself ( and others) went with JsonIgnore is that this is the attribute used by Newtonsoft Json and it actually worked in one scenario. If there had been documentation telling me to use some other attribute, I would have used that.

Another thing that would help me greatly is consistency and absence of land mines. For example, currently, JsonIgnore works in one scenario (no $expand), but fails silently in another scenario (using $expand). From my application developer point of view, there is no obvious difference between those scenarios. At minimum I would like to see an exception when you use for example JsonIgnore in a scenario where that is not supported instead of it failing silently.

**Comment by julealgon** [comment] 2022-11-08 12:20
> Using the standard serializer (by this I assume you're referring to System.Text.Json) to interpret $expand and other query options would be non-trivial.

@habbes this will need to be prioritized at some point... it is by far the aspect that brings the most confusion about using OData from my experience. So many people think that the default serializer is used... and I don't blame them: it would be the standard best practice for any "framework extension" to honor the configured serializer, but OData does not.

Pretty much all alternatives will end up feeling convoluted and hacky without that in place IMHO.

**Comment by habbes** [comment] 2022-11-14 13:42
@julealgon we've been working to integrate the standard `Utf8JsonWriter` in the OData serializer. We're still discussing internally ways to improve the serializer. As part of it we're investing potential compatibilities with `System.Text.Json`. However, this would not be a trivial undertaking.

**Closed** 2022-12-09 17:35 UTC
Labels: bug
