### ISSUE TITLE
ASP.Net Core OData 8.0.10 WriterValidator

### ISSUE THREAD

**Issue by alberk8** [OData/AspNetCoreOData#613] opened 2022-06-04 08:27 UTC
**Assemblies affected**
ASP.NET Core OData 8.0.10

**Describe the bug**
I have upgraded a project from version 7.5 to 8.0 and getting error on return from the controller where the data source form MongoDB where the data for the remarks can be null.  

```
[14:20:13.043  ERR][0HMI586FBK71I:00000012] Microsoft.AspNetCore.Server.Kestrel: Connection id "0HMI586FBK7II", Request id "0HMI586FBK71I:00000012": An unhandled exception was thrown by the application.
Microsoft.OData.ODataException: The property 'Remarks[Nullable=False]' of type 'Edm.String' has a null value, which is not allowed.
   at Microsoft.OData.WriterValidationUtils.ValidateNullPropertyValue(IEdmTypeReference expectedPropertyTypeReference, String propertyName, IEdmModel model)
   at Microsoft.OData.WriterValidator.ValidateNullPropertyValue(IEdmTypeReference expectedPropertyTypeReference, String propertyName, Boolean isTopLevel, IEdmModel model)
   at Microsoft.OData.JsonLight.ODataJsonLightPropertySerializer.WriteNullPropertyAsync(ODataPropertyInfo property)
   at Microsoft.OData.JsonLight.ODataJsonLightPropertySerializer.WritePropertyAsync(ODataProperty property, IEdmStructuredType owningType, Boolean isTopLevel, IDuplicatePropertyNameChecker duplicatePropertyNameChecker, ODataResourceMetadataBuilder metadataBuilder)
   at Microsoft.OData.JsonLight.ODataJsonLightPropertySerializer.WritePropertiesAsync(IEdmStructuredType owningType, IEnumerable`1 properties, Boolean isComplexValue, IDuplicatePropertyNameChecker duplicatePropertyNameChecker, ODataResourceMetadataBuilder metadataBuilder)
   at Microsoft.OData.JsonLight.ODataJsonLightWriter.StartResourceAsync(ODataResource resource)
   at Microsoft.OData.ODataWriterCore.<>c.<<WriteStartResourceImplementationAsync>b__196_0>d.MoveNext()
```

**Reproduce steps**

**Data Model**
```
public class Grade 
{
   public string Subject {get;set;}="";
   public string Remarks {get;set;} ="";
   public int Score {get;set;}
}

public class Student
{
   [Key]
   public Guid ID {get;set;}
   public String Name {get;set;} = "";
   public Grade Grade {get;set;}
}
```

**EDM (CSDL) Model**

**Request/Response**

**Expected behavior**
Return data without validating the property for null.

**Screenshots**

**Additional context**
By adding `Request.GetWriterSettings().Validations = Microsoft.OData.ValidationKinds.None;` in the controller the error will go away.  
Is there a global setting for this?.

**Comment by julealgon** [comment] 2022-06-06 17:43
Why not mark the property as nullable in the EDM instead?

**Comment by alberk8** [comment] 2022-06-07 00:41
> Why not mark the property as nullable in the EDM instead?

I would be a massive undertakings as I have hundreds of collections(tables) in the MongoDB.

**Comment by julealgon** [comment] 2022-06-07 13:02
> I am already doing this, what else can I add to make non nullable property to nullable.

Just indicate the property can be nullable using nullable reference types.

Instead of this:
```csharp
public class Grade 
{
   public string Subject {get;set;}="";
   public string Remarks {get;set;} ="";
   public int Score {get;set;}
}
```

Do this:
```csharp
public class Grade 
{
   public string Subject {get;set;}="";
   public string? Remarks {get;set;} ="";
   public int Score {get;set;}
}
```
`Remarks` will then be marked as nullable.

**Comment by julealgon** [comment] 2022-06-07 16:59
> @julealgon Put '?' after string type in `public string? Remarks` don't affect the nullability when building the Edm model.

@xuzhg , either you are incorrect here, or I'm missing something. 

Here are my tests in a sample project:

```csharp
public sealed class WeatherForecast
{
    public Guid Id { get; set; }

    public DateTime Date { get; set; }

    public int TemperatureC { get; set; }

    public int TemperatureF => 32 + (int)(this.TemperatureC / 0.5556);

    public string? Summary { get; set; }
}
```

```xml
<EntityType Name="WeatherForecast">
	<Key>
		<PropertyRef Name="Id"/>
	</Key>
	<Property Name="Id" Type="Edm.Guid" Nullable="false"/>
	<Property Name="Date" Type="Edm.DateTimeOffset" Nullable="false"/>
	<Property Name="TemperatureC" Type="Edm.Int32" Nullable="false"/>
	<Property Name="Summary" Type="Edm.String"/>
</EntityType>
```

Notice the `Summary` property: it is `string?` (using nullable reference types), and my EDM is showing it as nullable (i.e. no nullable annotation at all).

If I change the model to this:
```csharp
public sealed class WeatherForecast
{
    public Guid Id { get; set; }

    public DateTime Date { get; set; }

    public int TemperatureC { get; set; }

    public int TemperatureF => 32 + (int)(this.TemperatureC / 0.5556);

    public string Summary { get; set; } = null!;
}
```

I get the following metadata now in the `$metadata` endpoint:
```xml
<EntityType Name="WeatherForecast">
	<Key>
		<PropertyRef Name="Id"/>
	</Key>
	<Property Name="Id" Type="Edm.Guid" Nullable="false"/>
	<Property Name="Date" Type="Edm.DateTimeOffset" Nullable="false"/>
	<Property Name="TemperatureC" Type="Edm.Int32" Nullable="false"/>
	<Property Name="Summary" Type="Edm.String" Nullable="false"/>
</EntityType>
```

I'm not touching the EDM here in any way between runs: I just changed the property from `string` to `string?`.

**Comment by alberk8** [comment] 2022-06-08 00:52
Thank you for the explaining the issue.   It looks like I have two options.

1)  No change to schema (POCO), need to add `Request.GetWriterSettings().Validations = Microsoft.OData.ValidationKinds.None`  to the controller.
2) Change POCO to allow null.

**Comment by xuzhg** [comment] 2022-06-08 22:19
@julealgon I found the root cause. It's related to `#nullable enabled` ( new C# 8 feature).

The new model builder introduced two nullable conventions to handle `#nullable enabled`. 
- https://github.com/OData/ModelBuilder/blob/main/src/Microsoft.OData.ModelBuilder/Conventions/Attributes/NullableContex[tAttributeEdmTypeConvention.cs]
- https://github.com/OData/ModelBuilder/blob/main/src/Microsoft.OData.ModelBuilder/Conventions/Attributes/NullableAttributeEdmPropertyConvention.cs

If #nullable enable, reference type property without '?' suffix is treated as `non-nullable`, meanwhile with '?' is treated as nullable. I forgot new model builder implemented this feature.

See detail at: https://github.com/OData/ModelBuilder/pull/17
also see examples at: https://github.com/OData/ModelBuilder/tree/main/test/Microsoft.OData.ModelBuilder.Tests/TestModels/NonNullable

@alberk8 If you disable the nullable reference type, you should get the correct result.
To disable nullable reference type, open the csproj file and remove the following:

`< Nullable >enable< /Nullable >`

Hope it can help.

@dxrdxr For your information.

**Comment by dxrdxr** [comment] 2022-06-10 21:53
@alberk8 Another less intrusive option is to surround your data structure definitions with `nullable disable` and `nullable restore` pairs which will allow your code to generally take advantage of non-nullable reference types but not impact the externally defined data types.

**Closed** 2022-06-14 16:36 UTC
Labels: bug, investigated
