### ISSUE TITLE
[EnableQuery] attribute fails on .NET5 web api

### ISSUE THREAD

**Issue by nilobarp** [OData/AspNetCoreOData#66] opened 2021-01-09 15:46 UTC
I am trying to add OData to a .net5 web API but once added the endpoints starts throwing `ArgumentNullException`

### Assemblies affected

OData WebApi lib 8.0.0-preview3

### Reproduce steps

- Create a new .net 5 web API project
- Add Microsoft.AspNetCore.OData (8.0.0-preview3) from Nuget
- In Startup.cs add `services.AddOData();`
- In any controller method add [EnableQuery] attribute

### Expected result

The endpoint should work with OData or at least with simple query parameters.

### Actual result

It throws the following stack trace when a query parameter is added to the URL.

The endpoint works normally if there are no query parameters. Say the URL is `/weather-forecast` then `/weather-forecast?q=123456` will fail with the following stack trace.

```
System.ArgumentNullException: Value cannot be null. (Parameter 'key')
   at System.Collections.Generic.Dictionary`2.FindValue(TKey key)
   at System.Collections.Generic.Dictionary`2.ContainsKey(TKey key)
   at Microsoft.AspNetCore.OData.ODataOptions.GetODataServiceProvider(String prefix)
   at Microsoft.AspNetCore.OData.Extensions.HttpRequestExtensions.GetSubServiceProvider(HttpRequest request)
   at Microsoft.AspNetCore.OData.Query.ODataQueryOptions..ctor(ODataQueryContext context, HttpRequest request)
   at Microsoft.AspNetCore.OData.Query.EnableQueryAttribute.CreateAndValidateQueryOptions(HttpRequest request, ODataQueryContext queryContext)
   at Microsoft.AspNetCore.OData.Query.EnableQueryAttribute.ExecuteQuery(Object responseValue, IQueryable singleResultCollection, ControllerActionDescriptor actionDescriptor, HttpRequest request)
   at Microsoft.AspNetCore.OData.Query.EnableQueryAttribute.OnActionExecuted(ActionExecutedContext actionExecutedContext, Object responseValue, IQueryable singleResultCollection, ControllerActionDescriptor actionDescriptor, HttpRequest request)
   at Microsoft.AspNetCore.OData.Query.EnableQueryAttribute.OnActionExecuted(ActionExecutedContext actionExecutedContext)
   at Microsoft.AspNetCore.Mvc.Filters.ActionFilterAttribute.OnActionExecutionAsync(ActionExecutingContext context, ActionExecutionDelegate next)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at SharedLib.Auth.ExtractJwtMiddleware.Invoke(HttpContext context) in /Users/nilotpal/code/preventure/live/stratos/Src/SharedLib/Auth/ExtractJwtMiddleware.cs:line 40
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

**Comment by lukas-gmuer** [comment] 2021-01-14 13:17
Can confirm, happened to me too.

The null value comes from request.ODataFeature().PrefixName.
The edmModel that is built was not registered in the OdataOptions.
The built edmModel did not pass the validation as the properties did not allow certain filter operations.

I forked the project and got it to work for my use case. It's however dirty code and not the right place to do these things.

https://github.com/lukas-gmuer/AspNetCoreOData/commit/2c25162b11b1479bd13dff4d3ccf2f60b4b58d51

**Comment by trevoirwilliams** [comment] 2021-01-16 14:30
This is my Startup.cs

`public void ConfigureServices(IServiceCollection services)
        {
            services.AddDbContext<DatabaseContext>(options =>
                options.UseSqlServer(Configuration.GetConnectionString("sqlConnection"))
            );
            services.AddControllers();
            services.AddOData(opt => opt.AddModel("odata", GetEdmModel()));

            services.AddAuthentication();
        }
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            app.UseRouting();
            app.UseAuthentication();
            app.UseAuthorization();
            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers();
            });
            
        }

        private static IEdmModel GetEdmModel()
        {
            ODataConventionModelBuilder builder = new ODataConventionModelBuilder();
            builder.EntitySet<tbl1>("tbl1");
            builder.EntitySet<tbl2>("tbl2");
            return builder.GetEdmModel();
        }
`

I have this issue too. Once [EnableQuery] is on an endpoint I get  the following:

> System.ArgumentNullException: Value cannot be null. (Parameter 'key')
   at System.Collections.Generic.Dictionary`2.FindValue(TKey key)
   at System.Collections.Generic.Dictionary`2.ContainsKey(TKey key)
   at Microsoft.AspNetCore.OData.ODataOptions.GetODataServiceProvider(String prefix)
   at Microsoft.AspNetCore.OData.Extensions.HttpRequestExtensions.GetSubServiceProvider(HttpRequest request)
   at Microsoft.AspNetCore.OData.Query.ODataQueryOptions..ctor(ODataQueryContext context, HttpRequest request)
   at Microsoft.AspNetCore.OData.Query.EnableQueryAttribute.CreateAndValidateQueryOptions(HttpRequest request, ODataQueryContext queryContext)
   at Microsoft.AspNetCore.OData.Query.EnableQueryAttribute.ExecuteQuery(Object responseValue, IQueryable singleResultCollection, ControllerActionDescriptor actionDescriptor, HttpRequest request)
   at Microsoft.AspNetCore.OData.Query.EnableQueryAttribute.OnActionExecuted(ActionExecutedContext actionExecutedContext, Object responseValue, IQueryable singleResultCollection, ControllerActionDescriptor actionDescriptor, HttpRequest request)
   at Microsoft.AspNetCore.OData.Query.EnableQueryAttribute.OnActionExecuted(ActionExecutedContext actionExecutedContext)
   at Microsoft.AspNetCore.Mvc.Filters.ActionFilterAttribute.OnActionExecutionAsync(ActionExecutingContext context, ActionExecutionDelegate next)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

**Comment by xuzhg** [comment] 2021-01-21 21:29
@trevoirwilliams do you have a repro

**Comment by jashmehta-qds** [comment] 2021-01-24 11:58
I am having the same issue. When using [EnableQuery] to my get methods, I have the same stack trace.

**Comment by jashmehta-qds** [comment] 2021-01-26 05:42
@xuzhg would it be possible if I could share to my repo ?

**Comment by xuzhg** [comment] 2021-01-26 18:01
@jashmehta-qds Yes, please

**Comment by jashmehta-qds** [comment] 2021-01-28 09:02
> @jashmehta-qds Yes, please
[startup.cs](https://github.com/jashmehta-qds/TEST-MulltiTenantAPI-Demo/blob/master/TEST_MulltiTenantAPI_Demo.Api/Startup.cs)

**Comment by MarkZither** [comment] 2021-01-31 21:53
I had the same error, what I noticed that is different between the working sample project and @jashmehta-qds and my controllers is the get method, in the same it is just Get
```
        [HttpGet]
        [EnableQuery]
        public IActionResult Get(CancellationToken token)
        {
            return Ok(_persons);
        }
```
i had something like 
```
        [HttpGet]
        [EnableQuery]
        [SwaggerOperation("GetFiles")]
        [SwaggerResponse((int)HttpStatusCode.OK)]
        [SwaggerResponse((int)HttpStatusCode.NotFound)]
        public IActionResult GetFiles()
        {
             ...
            return Ok(Files);
        }
```
I added the `ODataRouteHandler` to debug what was happening and the route for `GetFiles` was not listed, once i changed it to just `Get` it started working.

Does the controller name have to match the model too? Just the difference between `CDNFileInfoController` and `CDNFileInfoAsyncController` seems to enough to lead to the error.

**Comment by AndreasGaus** [comment] 2021-02-01 12:51
> I am having the same issue. When using [EnableQuery] to my get methods, I get the same stack trace.
> 
> ```
> System.ArgumentNullException: Value cannot be null. (Parameter 'key')
>    at System.Collections.Generic.Dictionary`2.FindValue(TKey key)
>    at System.Collections.Generic.Dictionary`2.ContainsKey(TKey key)
>    at Microsoft.AspNetCore.OData.ODataOptions.GetODataServiceProvider(String prefix)
>    at Microsoft.AspNetCore.OData.Extensions.HttpRequestExtensions.GetSubServiceProvider(HttpRequest request)

Same issue happened to me. Tried to read all available OData / ASP.NET Core documentation available so far, without success.
Workaround: remove [EnableQuery], but then the OData query extensions are not handled any more.

**Comment by trevoirwilliams** [comment] 2021-02-01 15:02
> @trevoirwilliams do you have a repro

Not anymore. I deployed without it.

**Comment by AndreasGaus** [comment] 2021-02-01 17:10
> > @trevoirwilliams do you have a repro
> 
> Not anymore. I deployed without it.

Does this mean, [EnableQuery] is not working with 8.x by design?

**Comment by trevoirwilliams** [comment] 2021-02-01 19:19
> > > @trevoirwilliams do you have a repro
> > 
> > Not anymore. I deployed without it.
> 
> Does this mean, [EnableQuery] is not working with 8.x by design?

That has been my experience. I was even considering implementing the previous version.

**Comment by xuzhg** [comment] 2021-02-01 21:59
@jashmehta-qds "GetAll" is not odata routing convention. So, it maps to the non-odata routing. that's not working.

**Comment by xuzhg** [comment] 2021-02-01 22:00
@MarkZither "Get" is naming convention for OData routing convention.

**Comment by xuzhg** [comment] 2021-02-01 22:01
@AndreasGaus @trevoirwilliams enable query works with the odata routing with edm model.

**Comment by AndreasGaus** [comment] 2021-02-02 13:39
> @AndreasGaus @trevoirwilliams enable query works with the odata routing with edm model.

I use an own EF model  with MVC controller for REST (derived from Microsoft.AspNetCore.OData.Routing.Controllers.**MetadataController**) side by side with an EDM model. The EDM model is only used for the $ extensions for filtering (https://docs.microsoft.com/en-us/dynamics-nav/using-filter-expressions-in-odata-uris) sorting etc.

This mix of our own endpoint model plus OData $ extensions does not work anymore because of the [EnableQuery] triggered exception (GetSubServiceProvider -> Find Value -> Value cannot be null). The answers above direct to an issue with the new endpoint routing concepts in OData 8.x.

We originally decided to go to OData 8.x when .NET 5 migration of our .NET Core 3.1 project has been requested.
Probably we have to drop OData filtering, sorting etc. now and remove OData dependency from our REST based server, because in the near future OData team will not support [EnableQuery] in the same way as in former releases?

**Comment by kakone** [comment] 2021-09-17 08:56
> enable query works with the odata routing with edm model.

Is there any chance to make it work without edm model ?
I don't use edm model, I spent several days trying to migrate to OData 8 and it's a nightmare.

**Comment by anranruye** [comment] 2021-09-17 10:36
@kakone https://devblogs.microsoft.com/odata/up-running-w-odata-in-asp-net-6/ this blog may help

**Comment by Budsy** [comment] 2021-10-30 23:37
in my GetEdmModel() method I used
builder.Singleton<T>("name");
instead of builder.EntitySet<T>, mostly because my model is not an EntityFrameword entity... I build the model dynamically from a Json source, and map it to a POCO object.

**Comment by xuzhg** [comment] 2022-01-12 19:19
I'd close this issue. Please file a new issue if you have further concerns or questions. thanks a lot.

**Closed by xuzhg** 2022-01-12 19:19 UTC
