### ISSUE TITLE
Post does not return related properties

### ISSUE THREAD

**Issue by koshdim** [OData/AspNetCoreOData#267] opened 2021-07-30 14:39 UTC
OData 7.5.8, Asp Core 3.1 application,
Controller inherits ODataController, the method defined like this:
```
[EnableQuery]
        [ODataRoute]
        public async Task<IActionResult> Post([FromBody] TModel model)
        {
            var createdItem = await _service.CreateAsync(model).ConfigureAwait(false);
            return Created(createdItem);
        }
```
EDM is defined like this:

```
var odataBuilder = new ODataConventionModelBuilder();
            odataBuilder.EnableLowerCamelCase();
           // odataBuilder.AddOdataRoute<Model>(nameof(ModelsController));
            odataBuilder.EntitySet<Model>("Models");
            return odataBuilder.GetEdmModel();
```

I see in debug mode that createdItem contains collections of related items with several related models in them, but in Postman I see only plain object without relations.
POST request URL ends like this: /Models?$expand=Relations

What should I tweak to see all the properties in response?

**Comment by TehWardy** [comment] 2021-07-30 17:53
Interesting ... I thought it was just since .Net 5.0 as I had not been able to repro this under .Net Core 3.1 
Looks like my problem though: https://github.com/OData/AspNetCoreOData/issues/248

**Comment by gathogojr** [comment] 2021-08-03 17:19
@koshdim Can you swap the `IActionResult` with the concrete as the return type - `Model` in your case I think?

**Comment by koshdim** [comment] 2021-08-04 07:27
@gathogojr, I tried like this:

```
[EnableQuery]
        [ODataRoute]
        public async Task<CreatedODataResult<TModel>> Post([FromBody] TModel model)
        {
            var createdItem = await _service.CreateAsync(model).ConfigureAwait(false);
            return Created(createdItem);
        }
```
same result

**Comment by gathogojr** [comment] 2021-08-04 07:29
```csharp
public async Task<TModel> Post([FromBody] TModel model)
```

**Comment by koshdim** [comment] 2021-08-04 07:32
same

**Comment by gathogojr** [comment] 2021-08-04 07:57
@koshdim Check out this repro https://github.com/gathogojr/Repro267

**Comment by TehWardy** [comment] 2021-08-04 07:58
So we found this ...
```cs
        private static IEdmNavigationSource GetNavigationSource(IEdmModel model, IEdmType elementType, ODataPath odataPath)
        {
            Contract.Assert(model != null);
            Contract.Assert(elementType != null);
            IEdmNavigationSource navigationSource = (odataPath != null) ? odataPath.GetNavigationSource() : null;
            if (navigationSource != null)
            {
                return navigationSource;
            }
            IEdmEntityContainer entityContainer = model.EntityContainer;
            if (entityContainer == null)
            {
                return null;
            }
            List<IEdmEntitySet> matchedNavigationSources =
                entityContainer.EntitySets().Where(e => e.EntityType() == elementType).ToList();
            return (matchedNavigationSources.Count != 1) ? null : matchedNavigationSources[0];
        }
```
This little gem is in Query/ODataQueryContext.cs in the MicrosoftAspNetCoreOData project
It loks like if you do something like this ...

```cs
Builder.EntityType<T>().Collection.Action("Custom1").ReturnsCollectionFromEntitySet<Result<T>>(setName + "Results");
Builder.EntityType<T>().Collection.Action("Custom2").ReturnsCollectionFromEntitySet<Result<T>>(setName + "Results");
```
If the string passed in as the last parameter is different on each line then expands don't work properly and this is caused by the method above returning null as more than one navigation source is found.

Technically I suppose this is an issue in the model construction that the framework doesn't like but the framework is swallowing the problem here so we could probably do with some better validation feedback on our model configurations.

**Comment by koshdim** [comment] 2021-08-04 08:07
@TehWardy , there are no actions defined, I just use .AddOdataRoute() and that's it

**Comment by gathogojr** [comment] 2021-08-04 08:07
@TehWardy I believe your comment was intended for [this](https://github.com/OData/AspNetCoreOData/issues/248) issue, no?

**Comment by koshdim** [comment] 2021-08-04 08:12
@gathogojr, I use version 7.5.8.
8 is too unstable

**Comment by gathogojr** [comment] 2021-08-04 08:14
@koshdim Works in 7.5.8 too. You can downgrade and tweak the repro I shared to confirm

**Comment by koshdim** [comment] 2021-08-04 08:54
@gathogojr , yes, your example works. 
in my application there a lot of other things, like versioning, Swagger, EF etc, that may affect the issue. maybe I'll reproduce it on your solution later

**Comment by TehWardy** [comment] 2021-08-04 10:43
@gathogojr  seems to be applicable to both, I posted it on both for visibility too.
We have found that between v7.x and v8.x of the OData stuff it's largely all in sync now.

Drilling through the code though reveals some interesting changes in the behaviour.
the v7 builds were much more forgiving, v8 is brutally strict and often the problems are not with the framework but in the metadata / model definition we give it.

The biggest issue as I see it is in functionality that should work but doesn't for this reason and it's not clear to either framework side or our code dependent on it individually which is at fault.

We also found that after pulling down the source from here and running it as part of our solution there was a combination of things that led to new bugs in the functionality of our API that weren't strictly framework or our bugs but a sort of cross play of standards.

If I had one key take away from all this that I would want Microsoft / @xuzhg  and his team to look at it would be some sort of init code that could validate the EDM models better to determine some of these edge cases that we are seeing.
the main reasoning being here is that as a user experience it comes across like v7 did something fine and v8 is now not able to do that when in fact I think the real answer is way more complex and that in fact it might be one of the deps that this library has that's actually at fault.

Since this library is actually a sort of middleman it should probably have a middle ground approach and set a standard that it confirms both sides meet somehow ... not sure how though.

Along side that as per my feedback on this ticket (https://github.com/OData/AspNetCoreOData/issues/266) I think there's a lot that could be done to simplify or reduce the raw number of lines of code in the framework but I may have a simplified view of it and not fully appreciating what is completely going on with my limited experience on it.

**Comment by JanKotschenreuther** [comment] 2021-08-06 14:56
I do not know which NuGet-Package or Namespace makes use of `ODataConventionModelBuilder.AddOdataRoute<T>()`, so i were not able to check that method out, but I think, if you want to use the route ` {{baseUrl}}/Models` you need to tell your model builder the correct route `Models`:
```Csharp
var odataBuilder = new ODataConventionModelBuilder();
            odataBuilder.EnableLowerCamelCase();
            odataBuilder.AddOdataRoute<Model>("Models");
            return odataBuilder.GetEdmModel();
```

But you instead tell your model builder to use the route `nameof(ModelsController)`, which will create the route ` {{baseUrl}}/ModelsController`:
```Csharp
var odataBuilder = new ODataConventionModelBuilder();
            odataBuilder.EnableLowerCamelCase();
            odataBuilder.AddOdataRoute<Model>(nameof(ModelsController));
            return odataBuilder.GetEdmModel();
```

At least thats how `ODataConventionModelBuilder.EntitySet<T>()` works.

**Comment by julealgon** [comment] 2022-01-10 20:18
> @gathogojr, I tried like this:
> 
> ```
> [EnableQuery]
>         [ODataRoute]
>         public async Task<CreatedODataResult<TModel>> Post([FromBody] TModel model)
>         {
>             var createdItem = await _service.CreateAsync(model).ConfigureAwait(false);
>             return Created(createdItem);
>         }
> ```
> 
> same result

Does the expansion work if you change the code to something like this?
```
        [EnableQuery]
        [ODataRoute]
        public async Task<SingleResult<TModel>> Post([FromBody] TModel model)
        {
            var createdItem = await _service.CreateAsync(model).ConfigureAwait(false);
            return SingleResult.Create(new [] { createdItem }.AsQueryable());
        }
```

**Comment by TehWardy** [comment] 2022-02-03 10:17
Here's my base controller code that I inherit all my OData controllers from and I can confirm that testing reveals this works including all functions that enable query do expand properly ...

```cs
using Core.Objects;
using Core.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.OData.Deltas;
using Microsoft.AspNetCore.OData.Formatter;
using Microsoft.AspNetCore.OData.Query;
using Microsoft.AspNetCore.OData.Results;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Dynamic.Core;
using System.Security;
using System.Threading.Tasks;

namespace Web.Api
{
    public class EntityODataController<T, TKey, TUser> : CoreODataController, IDisposable
        where T : class
    {
        protected IService<T, TUser> Service { get; private set; }

        public EntityODataController(IService<T, TUser> service, IAuthInfo auth) : base(auth) => Service = service;

        [HttpGet]
        public virtual IActionResult GetMetadata() => Ok(GetMetadataForType(typeof(T), true, true));

        [HttpGet]
        [EnableQuery(
            AllowedArithmeticOperators = AllowedArithmeticOperators.All,
            AllowedFunctions = AllowedFunctions.AllFunctions,
            AllowedLogicalOperators = AllowedLogicalOperators.All,
            AllowedQueryOptions = AllowedQueryOptions.All,
            MaxAnyAllExpressionDepth = 3,
            MaxExpansionDepth = 3
        )]
        public virtual IActionResult Get(ODataQueryOptions<T> queryOptions) => Ok(Service.GetAll(false));

        [HttpGet]
        [AllowAnonymous]
        [EnableQuery(
            AllowedArithmeticOperators = AllowedArithmeticOperators.All,
            AllowedFunctions = AllowedFunctions.AllFunctions,
            AllowedLogicalOperators = AllowedLogicalOperators.All,
            AllowedQueryOptions = AllowedQueryOptions.All,
            MaxAnyAllExpressionDepth = 3,
            MaxExpansionDepth = 3
        )]
        public virtual IActionResult Get([FromODataUri] TKey key)
        {
            // do a get all call and then a where expression to get the one with the key
            var idEquals = typeof(T).IdEquals<T>(key);
            var result = Service.GetAll(false).AsQueryable().Where(idEquals);
            return (result != null) ? Ok(SingleResult.Create(result)) : NotFound();
        }

        [HttpPost]
        [EnableQuery(
            AllowedArithmeticOperators = AllowedArithmeticOperators.All,
            AllowedFunctions = AllowedFunctions.AllFunctions,
            AllowedLogicalOperators = AllowedLogicalOperators.All,
            AllowedQueryOptions = AllowedQueryOptions.All,
            MaxAnyAllExpressionDepth = 3,
            MaxExpansionDepth = 3
        )]
        public virtual async Task<IActionResult> Post([FromBody] T entity)
                => ModelState.IsValid ? Ok(await Service.AddAsync(entity)) : BadRequest(ModelState);

        [HttpPost]
        [EnableQuery(
            AllowedArithmeticOperators = AllowedArithmeticOperators.All,
            AllowedFunctions = AllowedFunctions.AllFunctions,
            AllowedLogicalOperators = AllowedLogicalOperators.All,
            AllowedQueryOptions = AllowedQueryOptions.All,
            MaxAnyAllExpressionDepth = 3,
            MaxExpansionDepth = 3
        )]
        public virtual async Task<IActionResult> AddAll([FromBody] ODataCollection<T> items)
        {
            if (ModelState.IsValid)
                return Ok(await Service.AddAllAsync(items.Value));
            else
                return BadRequest(ModelState);
        }

        [HttpPost]
        [EnableQuery(
            AllowedArithmeticOperators = AllowedArithmeticOperators.All,
            AllowedFunctions = AllowedFunctions.AllFunctions,
            AllowedLogicalOperators = AllowedLogicalOperators.All,
            AllowedQueryOptions = AllowedQueryOptions.All,
            MaxAnyAllExpressionDepth = 3,
            MaxExpansionDepth = 3
        )]
        public virtual async Task<IActionResult> UpdateAll([FromBody] ODataCollection<T> items)
            => ModelState.IsValid ? Ok((await Service.UpdateAllAsync(items.Value)).AsQueryable<Result<T>>()) : BadRequest(ModelState);



        [HttpPost]
        [EnableQuery(
            AllowedArithmeticOperators = AllowedArithmeticOperators.All,
            AllowedFunctions = AllowedFunctions.AllFunctions,
            AllowedLogicalOperators = AllowedLogicalOperators.All,
            AllowedQueryOptions = AllowedQueryOptions.All,
            MaxAnyAllExpressionDepth = 3,
            MaxExpansionDepth = 3
        )]
        public virtual async Task<IActionResult> AddOrUpdateAll([FromBody] ODataCollection<T> items)
            => ModelState.IsValid ? Ok(await Service.AddOrUpdate(items.Value)) : BadRequest(ModelState);

        [HttpPut]
        [EnableQuery(
            AllowedArithmeticOperators = AllowedArithmeticOperators.All,
            AllowedFunctions = AllowedFunctions.AllFunctions,
            AllowedLogicalOperators = AllowedLogicalOperators.All,
            AllowedQueryOptions = AllowedQueryOptions.All,
            MaxAnyAllExpressionDepth = 3,
            MaxExpansionDepth = 3
        )]
        public virtual async Task<IActionResult> Put([FromODataUri] TKey key, [FromBody] T entity)
        {
            try
            {
                return ModelState.IsValid? Ok(await Service.UpdateAsync(entity)) : BadRequest(ModelState);
            }
            catch(SecurityException ex)
            {
                return Unauthorized(new { error = ex.Message.Replace("\"", "\'") }.ToJson());
            }
        }

        [AcceptVerbs("PATCH", "MERGE")]
        public async Task<IActionResult> Patch([FromODataUri] TKey key, Delta<T> delta)
        {
            // don't like this, would rather pass the delta to the service layer but that would force a 
            // dependency on the OData framework in the business layer.
            var origentity = Service.Get(key);
            if (origentity == null)
                return NotFound();

            delta.Patch(origentity);
            return Ok(await Service.UpdateAsync(origentity));
        }

        [HttpDelete]
        public virtual async Task<IActionResult> Delete([FromODataUri] TKey key)
        {
            await Service.DeleteAsync(key);
            return Ok();
        }

        [HttpPost]
        public virtual async Task<IActionResult> DeleteAll([FromBody] ODataCollection<TKey> items)
        {
            if (ModelState.IsValid)
            {
                var workload = new List<Result<TKey>>();
                foreach (var key in items.Value)
                {
                    try
                    {
                        await Service.DeleteAsync(key);
                        workload.Add(new Result<TKey> { Item = key, Success = true, Message = "Done!" });
                    }
                    catch (Exception ex)
                    {
                        workload.Add(new Result<TKey> { Item = key, Success = false, Message = ex.Message });
                    }
                }
                return Ok(workload);
            }
            else
                return BadRequest(ModelState);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing && Service != null)
            {
                Service.Dispose();
                Service = null;
            }
        }
    }
}
```

This code is provided as is with no warrantees "you mileage may vary", ect ect ... 
If this doesn't resolve your issues then it's likely in your model somewhere, examine your entities and your model building code.

**Comment by KenitoInc** [comment] 2022-04-14 08:58
Seems issue was resolved @koshdim 
Closing this for now. In case of anything feel free to create a new issue

**Closed by KenitoInc** 2022-04-14 08:58 UTC
Labels: followup
