### ISSUE TITLE
ODataException: 'The request includes a $expand path which is too deep even MaxExpansionDepth is 0

### ISSUE THREAD

**Issue by komdil** [OData/AspNetCoreOData#1028] opened 2023-08-22 05:49 UTC
**Assemblies affected**
Microsoft.AspNetCore.OData 7.6.4

**Describe the bug**
I am using the routing convention and I am getting ODataException in some of my routes even when I set MaxExpansionDepth to 0 which will disable validation. (even I set 100,200,...). 

**Reproduce steps**
I couldn't reproduce it with a simple project. It is happening on my project that has complex configuration. I am configuring my custom Post request from the routing convention. I am creating a new EntitySetSegment based on some conditions and setting it to a path: 
```

                        var segmentsWithActions = segments.ToList();
                        segmentsWithActions.Add(actionEntitySetSegment);
                        feature.Path = new Microsoft.AspNet.OData.Routing.ODataPath(segmentsWithActions);
```

**Request/Response**
Query: http://localhost/odata/account/GetAmounts?$expand=AccountAmounts($expand=Account($select=Desc,Num;$expand=Category($select=Type)))

I am getting an error:  
`The request includes a $expand path which is too deep. The maximum depth allowed is 2. To increase the limit, set the 'MaxExpansionDepth' property on EnableQueryAttribute or ODataValidationSettings, or set the 'MaxDepth' property in ExpandAttribute.`

**Expected behavior**
I am expecting that query works because on top of my Controller I set: 

`[EnableQuery(MaxExpansionDepth = 0, EnsureStableOrdering = false, MaxNodeCount = 500)]`

**Comment by gathogojr** [comment] 2023-08-25 05:24
@komdil Thank you for reporting this to us. Investigating it is going to be tricky if you can't repro it in a simple project.
You have to at least be able to identify what's different in your complex project such that a different behaviour/outcome is being observed against that but not against a simple project.
Have you tried using Microsoft.AspNetCore.OData 7.7.1 - the latest 7.x release?
Can you try and create a repro that is a close to your actual project as possible that reproduces the behaviour?

**Comment by gathogojr** [comment] 2023-12-01 05:57
Closing since issue is unactionable as is. Feel free to reopen if you're able to share simple repro steps or project

**Closed by gathogojr** 2023-12-01 05:57 UTC
Labels: followup
