### ISSUE TITLE
Batch reference new entity error

### ISSUE THREAD

**Issue by andygjp** [OData/AspNetCoreOData#360] opened 2021-11-05 11:54 UTC
Hi,

I'm trying to create two entities and add a relationship between them in a single batch, like so:

```
POST http://localhost:5000/api/$batch
Content-Type: application/json

{
  "requests": [
    {
      "id": "1",
      "method": "POST",
      "url": "Suppliers",
      "headers": {
        "content-type": "application/json"
      },
      "body": {
        "CompanyName": "Paint Co"
      }
    },
    {
      "id": "2",
      "dependsOn": [ "1" ],
      "method": "POST",
      "url": "SalesProducts",
      "headers": {
        "content-type": "application/json"
      },
      "body": {
        "ShortDescription": "Paint"
      }
    },
    {
      "id": "3",
      "dependsOn": [ "1", "2" ],
      "method": "POST",
      "url": "$2/Suppliers/$ref",
      "headers": {
        "content-type": "application/json"
      },
      "body": {
        "@odata.id": "$1"
      }
    }
  ]
}
```

However, I get the following error:

```
System.InvalidOperationException: This operation is not supported for a relative URI.
   at System.Uri.get_Scheme()
   at Microsoft.AspNetCore.OData.Batch.HttpRequestExtensions.CopyAbsoluteUrl(HttpRequest request, Uri uri)
   at Microsoft.AspNetCore.OData.Batch.ODataBatchReaderExtensions.ReadOperationInternalAsync(ODataBatchReader reader, HttpContext originalContext, Guid batchId, Nullable`1 changeSetId, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.OData.Batch.ODataBatchReaderExtensions.ReadChangeSetRequestAsync(ODataBatchReader reader, HttpContext context, Guid batchId, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.OData.Batch.DefaultODataBatchHandler.ParseBatchRequestsAsync(HttpContext context)
   at Microsoft.AspNetCore.OData.Batch.DefaultODataBatchHandler.ProcessBatchAsync(HttpContext context, RequestDelegate nextHandler)
   at Microsoft.AspNetCore.OData.Batch.ODataBatchMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Microsoft.AspNetCore.OData.Routing.ODataRouteDebugMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

If I change the url of the third request from `$2/Suppliers/$ref` to relative url, eg: `SalesProducts/199/Suppliers/$ref`, there is no longer an error, but I need the entity I created in the second request, so its not an option. Plus, the reference in the body of the third request is not resolved. (Do I have to do that myself like in this example: https://docs.microsoft.com/en-us/aspnet/web-api/overview/odata-support-in-aspnet-web-api/odata-v4/entity-relations-in-odata-v4#creating-a-relationship-between-entities)

My question is: does microsoft.aspnetcore.odata version 8.0.3 support references or have I constructed the request incorrectly?

**Comment by andygjp** [comment] 2021-11-08 23:08
Hi,

I've created a very simple project to demonstrate the issue: https://github.com/andygjp/ODataBatchRefTest

**Comment by gathogojr** [comment] 2021-11-10 12:37
Duplicate of https://github.com/OData/AspNetCoreOData/issues/360

**Closed by gathogojr** 2021-11-10 12:37 UTC
