### ISSUE TITLE
Composite Key order

### ISSUE THREAD

**Issue by HeinA** [OData/AspNetCoreOData#235] opened 2021-07-15 09:57 UTC
'ello
I have a composite key defined as such:
			builder.EntitySet<Nmi.MasterData.CustomerSageAccountInfo>("CustomerSageAccountInfo")
				.EntityType
				.HasKey(x => new { x.CustomerId, x.AccountNumber });

When calling the controller the sequence of the keys seems to matter.  It does not work in the sequence I defined them.  It seems to want them in alphabetical order

this fails with 404
GET /OData/CustomerSageAccountInfo(CustomerId=6,AccountNumber='NM-FJE-NAS01')

this works:
/OData/CustomerSageAccountInfo(AccountNumber='NM-FJE-NAS01',CustomerId=6)

Is this by design?

**Comment by xuzhg** [comment] 2021-07-16 18:27
@HeinA That's by design. 

The built-in routing convention only builds template for one order (the property order in the type).

**Comment by HeinA** [comment] 2021-07-17 18:07
@xuzhg Thank you very much

**Comment by fw2568** [comment] 2022-01-12 17:15
@xuzhg are you sure that this answer is correct? 
You are most propably right that the route convention is build from key order but at least in my case the property order of keys was in alphabetical order even if properties where not. 

Like this:

``` xml
<Key>
<PropertyRef Name="DocumentNumber"/>
<PropertyRef Name="DocumentPart"/>
<PropertyRef Name="DocumentType"/>
<PropertyRef Name="DocumentVersion"/>
</Key>
<Property Name="DocumentType" Type="Edm.String" Nullable="false"/>
<Property Name="DocumentNumber" Type="Edm.String" Nullable="false"/>
<Property Name="DocumentPart" Type="Edm.String" Nullable="false"/>
<Property Name="DocumentVersion" Type="Edm.String" Nullable="false"/>
```

key was defined in same order as in type:

``` csharp
builder.EntityType<DocumentModel>().HasKey(x => new
    { x.DocumentType, x.DocumentNumber, x.DocumentPart, x.DocumentVersion });
```

I was able to workaround of this issue by setting property order:

``` csharp
builder.EntityType<DocumentModel>().Property(x => x.DocumentType).Order = 0;
builder.EntityType<DocumentModel>().Property(x => x.DocumentNumber).Order = 1;
builder.EntityType<DocumentModel>().Property(x => x.DocumentPart).Order = 2;
builder.EntityType<DocumentModel>().Property(x => x.DocumentVersion).Order = 3;

```

But I would also expect the keys to be generated in same order as defined. And this issue didn't exists in older versions of AspNetCore.OData as I noticed it after updating from 7.0.1 to 8.0.6.

**Comment by xuzhg** [comment] 2022-01-12 22:04
@fw2568 https://github.com/OData/AspNetCoreOData/blob/main/src/Microsoft.AspNetCore.OData/Routing/Template/KeySegmentTemplate.cs#L44 is the codes to generate the key template for routing.

**Comment by KenitoInc** [comment] 2022-04-14 09:03
The question was answered.
Closing this issue.

**Closed by KenitoInc** 2022-04-14 09:03 UTC
Labels: question, followup
