### ISSUE TITLE
Issue with filter operator while combining with groupby in odata on  .Net 6

### ISSUE THREAD

**Issue by suhasravva** [OData/AspNetCoreOData#723] opened 2022-10-21 08:28 UTC
**Assemblies affected**
 ASP.NET Core OData 8.x 
"Microsoft.AspNetCore.OData" Version="8.0.11"

**Describe the bug**
groupby with filter not working at all

http://localhost:5000/odata/Orders?$apply=groupby((Customer/Name), aggregate($count as OrderCount, TotalAmount with sum as TotalAmount))/filter(TotalAmount gt 23)   
http://localhost:5000/odata/Orders?$apply=groupby((Customer/Name), aggregate($count as OrderCount, TotalAmount with sum as TotalAmount))&$filter=TotalAmount gt 23
http://localhost:5000/odata/Orders?$filter=TotalAmount gt 23&$apply=groupby((Customer/Name), aggregate($count as OrderCount, TotalAmount with sum as TotalAmount))

**Reproduce steps**
Just trigger the apply groupby with filter you will see exception

**Data Model**
public class Customer
{
    public int Id { get; set; }
    public string Name { get; set; }
    public IList Emails { get; set; }
    public Address HomeAddress { get; set; }
    public IList
 FavoriteAddresses { get; set; }
    public Order PersonOrder { get; set; }
    public IList Orders { get; set; }
}

public class Order
{
    public int Id { get; set; }
    public string Title { get; set; }
    public decimal TotalAmount { get; set; }
    public Customer Customer { get; set; }
}

**EDM (CSDL) Model**
Please share your Edm model, for example, CSDL file.
You can send `$metadata` to get a CSDL XML content.

**Request/Response**
Please share your request Uri, head or the request body
Please share your response head, body.

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/13885744/197149707-1867b1bc-58c2-4e58-8271-8363ef030c09.png)

**Additional context**
These odata operators working fine on earlier 7 version (.net core 3.1) but on .net 6 with latest version of package its not working

**Comment by julealgon** [comment] 2022-10-21 12:50
@suhasravva Please double check existing issues before opening new ones.

Duplicate of:
- https://github.com/OData/AspNetCoreOData/issues/420

**Comment by suhasravva** [comment] 2022-10-26 14:15
duplicate item

**Closed** 2022-10-26 14:15 UTC
Labels: bug
